version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

formats:
#  - pdf # Disable the PDF option until PDF build process is reviewed.
  - htmlzip

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements_doc.txt
