docker:
  - image: cimg/python:3.11
    environment:
      PYPI_SMOKE_CODE: import synapse; print(synapse.version)
      PYTHON_TAG: py311

steps:
  - deploy_pypi_prologue
  - deploy_pypi_wheel_build
  - deploy_pypi_sdist_build
