description: Check that this runner has work to do
steps:
  - run:
      name: Check workload
      command: |
        mkdir -p ./tmp && \
        >./tmp/tests.txt && \
        circleci tests glob synapse/tests/test_*.py synapse/vendor/*/tests/test_*.py | circleci tests run --split-by=timings --command ">./tmp/tests.txt xargs echo"
        [ -s tmp/tests.txt ] || circleci-agent step halt #if there are no tests, terminate execution after this step
