description: "Execute unit tests via pytest"
steps:
  - run:
      name: run tests
      command: |
        . venv/bin/activate
        mkdir test-reports
        circleci tests glob synapse/tests/test_*.py synapse/vendor/*/tests/test_*.py | circleci tests run --split-by=timings --command "xargs python3 -m pytest -v -s -rs --durations 6 --maxfail 6 -p no:logging --junitxml=test-reports/junit.xml -o junit_family=xunit1 ${COVERAGE_ARGS}"
