import synapse.lib.syntax2 as s_syntax2

import synapse.tests.utils as s_t_utils
import lark

_Queries = [
    '',
    '#foo',
    'help',
    'refs',
    '#$tag',
    'wentto',
    '[-#foo]',
    'syn:tag',
    'teststr',
    '.created',
    '##baz.faz',
    'inet:fqdn',
    'inet:user',
    '#test.baz',
    '#hehe.haha',
    'inet:dns:a',
    'testint<20',
    'testint>20',
    'testint<30',
    'testint>30',
    'testint<=20',
    'testint>=20',
    'testint<=30',
    'teststr=foo',
    'teststr#foo',
    'pivcomp=$foo',
    'testint=1234',
    '[testint=20]',
    'teststr=$foo',
    'teststr=ohmy',
    '.created<2010',
    '.created>2010',
    'iden deadb33f',
    'testcomp -> *',
    'testint:loc=u',
    '[ testint=42 ]',
    'testint:loc=""',
    'testint:loc^=u',
    'testint:loc=us',
    'teststr~="zip"',
    '.created="2001"',
    '.seen~="^r"',
    'testint=8675309',
    '[testint=99999]',
    'testint:loc^=""',
    'testint:loc^=23',
    'testint +:loc=u',
    'testint:loc^=us',
    'teststr [-#foo]',
    'teststr#foo.bar',
    '[teststr=hello]',
    '.seen [ -.seen ]',
    'inet:ipv4:loc=us',
    'inet:ipv4:loc=zz',
    '#$tag [ -#$tag ]',
    'testint +:loc=""',
    'testint +:loc^=u',
    'testint +:loc=us',
    'testint:loc^=us.',
    'testint:loc=us.v',
    'teststr=bar <- *',
    '[ teststr=hehe ]',
    'teststr %limit=1',
    'teststr [-:tick]',
    'file:bytes:size=4',
    'movetag #a.b #a.m',
    'pivcomp:tick=$foo',
    'syn:tag=a.b +#foo',
    'testint +:loc^=""',
    'testint +:loc^=23',
    'testint +:loc^=us',
    'testint:loc^=us.v',
    'testint:loc=us.va',
    'teststr=bar <+- *',
    'teststr#foo@=2016',
    'teststr:tick=2015',
    'inet:fqdn=woot.com',
    '[ inet:ipv4=$foo ]',
    'pivcomp | noderefs',
    'pivcomp -> testint',
    'testint=3735928559',
    'testint +:loc^=us.',
    'testint +:loc=us.v',
    'testint:loc^=us.va',
    'teststr=foo <- has',
    'teststr=visi -> #*',
    'inet:user | limit 1',
    'movetag #hehe #woot',
    'pivcomp=(hehe,haha)',
    'testcomp -> testint',
    'testguid | max tick',
    'testguid | min tick',
    '[testint=3 :loc=""]',
    'testint +:loc^=us.v',
    'testint +:loc=us.va',
    'testint:loc^=us.va.',
    'testint +testint>10',
    'testint +testint<30',
    'teststr +#foo@=2016',
    'teststr [+#foo.bar]',
    'teststr=foo <+- has',
    'teststr +:tick=2015',
    '.created="{created}"',
    'inet:ipv4 -> teststr',
    'inet:user | limit 1|',
    '[pivcomp=(foo, 123)]',
    'syn:tag=foo.bar -> *',
    '[testint=12 :loc=us]',
    'testint +:loc^=us.va',
    'testint:loc=us.va.sy',
    'testint +testint>=10',
    'testint +testint<=30',
    'inet:dns:a :ipv4 -> *',
    'inet:ipv4=10.2.1.1/28',
    '[ inet:ipv4=1.2.3.4 ]',
    '[ pivcomp=(foo,bar) ]',
    'reindex --form-counts',
    '#test.bar -#test <- *',
    '#test.bar -#test -> *',
    'testint +:loc^=us.va.',
    '[ teststr=bar +#baz ]',
    '[ teststr=foo +#bar ]',
    'teststr=foo | delnode',
    'pivcomp=(foo,bar) -> *',
    'seen:source=$sorc -> *',
    'sudo | [ teststr=foo ]',
    '#test.bar -#test <+- *',
    '#test.bar -#test -+> *',
    'testcomp:haha~="^lulz"',
    'testcomp:haha~="^zerg"',
    'testint=123 | noderefs',
    'testint +:loc=us.va.sy',
    'teststr=123 | noderefs',
    'teststr=foobar -+> has',
    '[ teststr=foo +#$tag ]',
    '[ teststr=haha +#foo ]',
    'teststr +:tick@=(2015)',
    'teststr=visi -> #baz.*',
    'teststr=visi -> #foo.*',
    'pivcomp=(foo,bar) -+> *',
    'sudo | [ testguid="*" ]',
    '#test.bar +pivcomp -> *',
    '#test.bar +teststr <- *',
    '[testcomp=(1234, 5678)]',
    '[testint=10 :loc=us.va]',
    'testint:loc^=us.va.fair',
    'testint:loc=us.va.syria',
    'teststr=foo +#lol@=2014',
    'teststr=foo +#lol@=2016',
    'teststr | noderefs -d 3',
    '[ inet:fqdn = woot.com ]',
    'inet:ipv4=192.168.1.0/24',
    'inet:user | limit --woot',
    '#test.bar +pivcomp -+> *',
    '#test.bar +teststr <+- *',
    'testint:loc=us.va.sydney',
    'teststr#foo@=(2012,2022)',
    'inet:ipv4=1.2.3.1-1.2.3.3',
    'pivcomp | noderefs --join',
    '[testguid="*" :tick=2001]',
    'testint +:loc^=us.va.fair',
    'teststr | delnode --force',
    'teststr:tick<201808021202',
    'teststr:tick>201808021202',
    '[ teststr=woot .seen=20 ]',
    'teststr=woot +.seen@=2012',
    'teststr=woot +.seen@=2015',
    'teststr=woot +.seen@=#bar',
    'teststr=woot +.seen@=#baz',
    'inet:ipv4=1.2.3.4|limit 20',
    'inet:ipv4 +:asn::name=visi',
    'inet:ipv4 | reindex --subs',
    'sudo | testint=6 | delnode',
    'syn:tag=aaa.barbarella.ddd',
    'syn:tag=foo.bar -> teststr',
    '[testguid=abcd :tick=2015]',
    'testint=123 | noderefs -te',
    '[testint=9 :loc=us.ओं]',
    'testint:loc^=us.va.fairfax',
    'testint +:loc=us.va.sydney',
    'teststr="foo bar" +teststr',
    'teststr | noderefs -d 3 -u',
    'teststr +:tick@=("-1 day")',
    'teststr:tick<=201808021202',
    'teststr:tick>=201808021202',
    '.created*range=(2010, 3001)',
    '[ inet:asn=200 :name=visi ]',
    '[ inet:fqdn=woot.com ] -> *',
    '[inet:ipv4=1.2.3.1-1.2.3.3]',
    '[ inet:ipv4=192.168.1.0/24]',
    'pivtarg=hehe [ .seen=2015 ]',
    'ps:person=$pers -> has -> *',
    '[ testguid="*" :tick=2015 ]',
    '[ testguid="*" :tick=2016 ]',
    '[ testguid="*" :tick=2017 ]',
    'testint:loc^=us.va.fairfax.',
    'teststr=bar -> pivcomp:lulz',
    '[teststr=beep teststr=boop]',
    'teststr +#foo@=(2014, 2019)',
    'teststr +#foo@=(2015, 2018)',
    '[ teststr=foo teststr=bar ]',
    '[ teststr=haha +#bar=2015 ]',
    '[ teststr=haha +#bar=2016 ]',
    '.created*range=("2010", "?")',
    'geo:place=$place <- has <- *',
    'inet:fqdn=woot.com | delnode',
    'pivcomp=(foo,bar) -> pivtarg',
    'seen:source=$sorc :node -> *',
    'sudo | [ inet:ipv4=1.2.3.4 ]',
    'sudo | [ teststr=foo +#lol ]',
    'testcomp -> * | uniq | count',
    '[testint=1 :loc=us.va.syria]',
    'testint +:loc^=us.va.fairfax',
    'testint +:loc="us.va. syria"',
    'teststr=bar -+> pivcomp:lulz',
    'teststr="foo bar" [ -:tick ]',
    'teststr=hello [:tick="2001"]',
    'teststr=hello [:tick="2002"]',
    '[ inet:ipv4=1.2.3.4 :asn=20 ]',
    'inet:user | limit 1    |     ',
    'pivcomp=(foo,bar) -+> pivtarg',
    'syn:tag=baz.faz [ +#foo.bar ]',
    '[testint=2 :loc=us.va.sydney]',
    'testint +:loc^=us.va.fairfax.',
    '[ inet:ipv4=1.2.3.4 :asn=200 ]',
    'movetag #aaa.b #aaa.barbarella',
    'pivcomp | noderefs --join -d 3',
    'ps:person=$pers -> wentto -> *',
    '[testint=4 :loc=us.va.fairfax]',
    '$bar=5.5.5.5 [ inet:ipv4=$bar ]',
    '[ inet:dns:a=$blob.split("|") ]',
    'inet:ipv4 -inet:ipv4=1.2.3.0/30',
    'inet:ipv4 +inet:ipv4=1.2.3.0/30',
    '[ pivcomp=(xxx,yyy) :width=42 ]',
    'sudo | [teststr=123 :tick=2018]',
    'syn:tag=foo.bar -> teststr:tick',
    '[testint=1 testint=2 testint=3]',
    '[testint=8 :loc=us.ca.sandiego]',
    'teststr +#foo@=(2014, 20141231)',
    'teststr [+#foo.bar=(2000,2002)]',
    'teststr="foo bar" -teststr:tick',
    '[ teststr="foo bar" :tick=2018]',
    'teststr +:tick=(2015, "+1 day")',
    'teststr +:tick@=(now, "-1 day")',
    '[ teststr=visi +#foo.bar ] -> #',
    'inet:fqdn=woot.com -> inet:dns:a',
    'inet:ipv4 +inet:ipv4=10.2.1.4/31',
    'inet:ipv4 +inet:ipv4=10.2.1.4/32',
    '[ pivcomp=(foo,bar) :tick=2018 ]',
    'teststr=foobar -> has <- teststr',
    '[teststr=foo :tick=201808021201]',
    'teststr | noderefs -d 3 --unique',
    'teststr +:tick@=(2015, "+1 day")',
    'teststr=woot +.seen@=(2012,2013)',
    'teststr=woot +.seen@=(2012,2015)',
    '[ inet:dns:a=(woot.com,1.2.3.4) ]',
    'pivcomp | noderefs -j --degrees 2',
    'sudo | [ cycle0=foo :cycle1=bar ]',
    'sudo | [ cycle1=bar :cycle0=foo ]',
    'testcomp +(:hehe<2 or :haha=foob)',
    'testcomp +(:hehe<2 or :haha=test)',
    'testcomp +(:hehe<2 or #meep.gorp)',
    'testint:loc^=us.va.fairfax.reston',
    "[ teststr=abcd :tick=2015 +#cool ]"
    'teststr=foobar -> has <+- teststr',
    'teststr=pennywise | noderefs -d 3',
    'teststr +:tick@=("now-1day", "?")',
    'teststr +:tick=($test, "+- 2day")',
    'pivcomp=(foo,bar) :lulz -> teststr',
    'pivcomp=(foo,bar) :targ -> pivtarg',
    'ps:person=$pers -> wentto :n2 -> *',
    'testcomp +(:hehe<2 and :haha=foob)',
    'testcomp +(:hehe<2 and :haha=test)',
    '[ teststr=foo +#bar ] +(not .seen)',
    '[ teststr=foo teststr=bar ] | spin',
    '[ teststr=hehe +#foo=(2014,2016) ]',
    '[teststr=hehe] | iden abcd | count',
    'teststr +teststr:tick<201808021202',
    'teststr +teststr:tick>201808021202',
    'teststr:tick=(20131231, "+2 days")',
    '[ teststr=woot +#foo=(2015,2018) ]',
    '[ teststr=woot .seen=(2014,2015) ]',
    'cluster=abcd | noderefs -d 2 --join',
    'pivcomp=(foo,bar) :lulz -+> teststr',
    'ps:person=$pers -> has -> geo:place',
    'ps:person=$pers -> has -> inet:ipv4',
    '[seen=(abcd, (teststr, pennywise))]',
    'testint +:loc^=us.va.fairfax.reston',
    'teststr [+#foo.bar=(2000,20020601)]',
    'teststr +teststr:tick<=201808021202',
    'teststr +teststr:tick>=201808021202',
    'teststr +:tick=(20150102, "-3 day")',
    'teststr +:tick=(20150201, "+1 day")',
    'teststr=woot $foo=#foo +.seen@=$foo',
    'geo:place:latlong*near=((0, 0), 50m)',
    'geo:place=$place <- has <- inet:ipv4',
    'geo:place=$place <- has <- ps:person',
    'inet:ipv4 +inet:ipv4=1.2.3.1-1.2.3.3',
    'inet:user | limit 10 | [ +#foo.bar ]',
    '[ inet:user=visi inet:user=whippit ]',
    'testint:loc^=us.va.fairfax.chantilly',
    'teststr +:tick=(20150102, "+- 2day")',
    'teststr +:tick@=(20150102, "-4 day")',
    'iden 2cdd997872b10a65407ad5fadfa28e0d',
    'pivcomp | noderefs --join --degrees 2',
    'testguid +testguid*range=(abcd, dcbe)',
    '[testint=5 :loc=us.va.fairfax.reston]',
    '[ teststr=visi testint=20 +#foo.bar ]',
    'inet:user | limit 10 | +inet:user=visi',
    'ps:person=$pers -> wentto -> inet:ipv4',
    '[testint=7 :loc=us.va.fairfax.herndon]',
    'testint +:loc^=us.va.fairfax.chantilly',
    'teststr=123 | noderefs --traverse-edge',
    '[ teststr=foo teststr=bar ] | sleep 10',
    '[ teststr=foo teststr=bar testint=42 ]',
    '[inet:dns:query=(tcp://1.2.3.4, "", 1)]',
    '[ inet:ipv4 = 94.75.194.194 :loc = nl ]',
    '[refs=((teststr, 123), (testint, 123))]',
    'source=8f1401de15918358d5247e21ca29a814',
    'testcomp +:haha*range=(grinch, meanone)',
    'teststr=123 [:baz="testguid:tick=2015"]',
    'teststr +:tick@=("now+2days", "-3 day")',
    '[ geo:place="*" :latlong=(-30.0,20.22) ]',
    '[ inet:fqdn=woot.com +#bad=(2015,2016) ]',
    'teststr=1234 teststr=duck teststr=knight',
    'teststr=pennywise | noderefs --join -d 9',
    '[has=((teststr, foobar), (teststr, foo))]',
    'inet:dns:a=(woot.com,1.2.3.4) $newp=.seen',
    '[ inet:dns:a=(woot.com, 1.2.3.4) +#yepr ]',
    '[ teststr=foo +#bar ] { [ +#baz ] -#bar }',
    'teststr +:tick@=(20150102+1day, "-4 day")',
    'teststr +:tick*range=(19701125, 20151212)',
    '[ inet:ipv4=1.2.3.0/30 inet:ipv4=5.5.5.5 ]',
    'teststr=bar pivcomp=(foo,bar) [+#test.bar]',
    '[ teststr=foo +#bar ] +(#baz or not .seen)',
    'teststr=pennywise | noderefs -d 3 -ot=omit',
    'for $fqdn in $fqdns { [ inet:fqdn=$fqdn ] }',
    'inet:dns:a -{ :ipv4 -> inet:ipv4 -:loc=us }',
    'inet:dns:a -{ :ipv4 -> inet:ipv4 +:loc=us }',
    'inet:dns:a +{ :ipv4 -> inet:ipv4 -:loc=us }',
    'inet:dns:a +{ :ipv4 -> inet:ipv4 +:loc=us }',
    '[ inet:dns:a = ( woot.com , 12.34.56.78 ) ]',
    '[ inet:fqdn=vertex.link inet:ipv4=1.2.3.4 ]',
    'inet:ipv4=1.2.3.4 +( { -> inet:dns:a }<=1 )',
    'inet:ipv4=1.2.3.4 +( { -> inet:dns:a }>=3 )',
    '[ testcomp=(10, haha) +#foo.bar -#foo.bar ]',
    'teststr=a +:tick*range=(20000101, 20101201)',
    '[ inet:dns:a=(vertex.link, 5.5.5.5) +#nope ]',
    '[ testcomp=(127,newp) ] [testcomp=(127,127)]',
    '[testint=6 :loc=us.va.fairfax.restonheights]',
    '[teststr=a] switch $woot { hehe: {[+#baz]} }',
    'teststr=pennywise | noderefs -d 3 -of=source',
    'geo:place:latlong*near=((34.1, -118.3), 10km)',
    'inet:dns:a +{ :ipv4 -> inet:ipv4 -:asn=1234 }',
    'inet:dns:a +{ :ipv4 -> inet:ipv4 +:asn=1234 }',
    'inet:fqdn=woot.com -> inet:dns:a -> inet:ipv4',
    'pivcomp=(foo,bar) -{ :lulz -> teststr +#baz }',
    'teststr=pennywise | noderefs -d 3 -otf=source',
    '[ teststr=visi +#foo.bar ] -> # [ +#baz.faz ]',
    'geo:place -:latlong*near=((34.1, -118.3), 50m)',
    'inet:asn=10 | noderefs -of inet:ipv4 --join -d 3',
    'teststr +:bar*range=((teststr, c), (teststr, q))',
    '[ teststr=oof +#bar ] { [ testint=0xdeadbeef ] }',
    'inet:ipv4=12.34.56.78 [ :loc = us.oh.wilmington ]',
    'teststr=pennywise | noderefs -d 3 --omit-tag=omit',
    '[ inet:dns:a=(woot.com,1.2.3.4) .seen=(2015,2016) ]',
    'inet:dns:a=(woot.com,1.2.3.4) [ .seen=(2015,2018) ]',
    '[inet:dns:query=(tcp://1.2.3.4, "foo*.haha.com", 1)]',
    '[ pivcomp=(hehe,haha) :tick=2015 +#foo=(2014,2016) ]',
    '[refs=((testint, 16), (testcomp, (9999, greenham)))]',
    'teststr=pennywise | noderefs -d 3 --omit-form=source',
    '[ teststr=woot +#foo=(2015,2018) .seen=(2014,2016) ]',
    '[testcomp=(3, foob) +#meep.gorp +#bleep.zlorp +#cond]',
    'inet:dns:a=(woot.com,1.2.3.4) $hehe=:fqdn -:fqdn=$hehe',
    'inet:dns:a=(woot.com,1.2.3.4) $hehe=:fqdn +:fqdn=$hehe',
    'pivcomp=(foo,bar) +{ :lulz -> teststr +#baz } +pivcomp',
    'geo:place +geo:place:latlong*near=((34.1, -118.3), 10km)',
    'inet:dns:query=(tcp://1.2.3.4, "", 1) :name -> inet:fqdn',
    '[source=abcd +#omit.nopiv] [seen=(abcd, (pivtarg, foo))]',
    'teststr=pennywise | noderefs --join -d 9 --traverse-edge',
    'inet:dns:a=(woot.com,1.2.3.4) $hehe=:fqdn inet:fqdn=$hehe',
    '[inet:ipv4=1.2.3.4 :asn=10] [seen=(abcd, (inet:asn, 10))]',
    '[teststr=c] switch $woot { hehe: {[+#baz]} *: {[+#jaz]} }',
    'geo:place:latlong*near=(("34.118560", "-118.300370"), 50m)',
    'ps:person=$pers -> wentto +:time@=(2014,2017) -> geo:place',
    '[ teststr=woot +#foo=(2015,2018) +#bar .seen=(2014,2016) ]',
    'teststr=pennywise | noderefs -d 3 -ott=omit.nopiv -ott=test',
    'for ($fqdn, $ipv4) in $dnsa { [ inet:dns:a=($fqdn,$ipv4) ] }',
    'geo:place:latlong*near=(("34.118560", "-118.300370"), 2600m)',
    'testcomp +testcomp*range=((1024, grinch), (4096, zemeanone))',
    '[ inet:ipv4=1.2.3.4 :loc=us inet:dns:a=(vertex.link,1.2.3.4) ]',
    '[ inet:ipv4=4.3.2.1 :loc=zz inet:dns:a=(example.com,4.3.2.1) ]',
    'teststr=pennywise | noderefs -d 3 --omit-traversal-form=source',
    'pivcomp=(hehe,haha) $ticktock=#foo -> pivtarg +.seen@=$ticktock',
    "[testcomp=(123, test) testcomp=(123, duck) testcomp=(123, mode)]"
    'for ($fqdn,$ipv4,$boom) in $dnsa { [ inet:dns:a=($fqdn,$ipv4) ] }',
    'inet:fqdn +#bad $fqdnbad=#bad -> inet:dns:a:fqdn +.seen@=$fqdnbad',
    'media:news = 00a1f0d928e25729b9e86e2d08c127ce [ :summary = \"\" ]',
    '[refs=((testcomp, (2048, horton)), (testcomp, (4096, whoville)))]',
    'teststr +:.seen*range=((20090601, 20090701), (20110905, 20110906,))',
    '[ inet:dns:a=(woot.com, 1.2.3.4) inet:dns:a=(vertex.link, 1.2.3.4) ]',
    'refs +:n1*range=((testcomp, (1000, green)), (testcomp, (3000, ham)))',
    'inet:dns:query=(tcp://1.2.3.4, "foo*.haha.com", 1) :name -> inet:fqdn',
    'inet:dns:a = (woot.com,  12.34.56.78) [ .seen=( 201708010123, \"?\" ) ]',
    'testint | noderefs | +testcomp*range=((1000, grinch), (4000, whoville))',
    '[refs=((testcomp, (9001, "A mean one")), (testcomp, (40000, greeneggs)))]',
    'inet:dns:a=(woot.com,1.2.3.4) $seen=.seen :fqdn -> inet:fqdn [ .seen=$seen ]',
    '[ inet:fqdn=woot.com inet:fqdn=vertex.link ] [ inet:user = :zone ] +inet:user',
    'inet:dns:a = (woot.com,  12.34.56.78) [ .seen=( 201708010123, 201708100456 ) ]',
    '[teststr=c] switch $woot { hehe: {[+#baz]} haha hoho: {[+#faz]} "lolz:lulz": {[+#jaz]} }',
    '[ inet:fqdn = hehe.com inet:ipv4 = 127.0.0.1 hash:md5 = d41d8cd98f00b204e9800998ecf8427e]',
    'teststr=pennywise | noderefs -d 3 --omit-traversal-tag=omit.nopiv --omit-traversal-tag=test',
    'geo:place=abcd $latlong=:latlong $radius=:radius | spin | tel:mob:telem:latlong*near=($latlong, 3km)',
    'inet:ipv4=12.34.56.78 inet:fqdn=woot.com [ inet:ipv4=1.2.3.4 :asn=10101 inet:fqdn=woowoo.com +#my.tag ]',
    '''
        for $foo in $foos {

            ($fqdn, $ipv4) = $foo.split("|")

            [ inet:dns:a=($fqdn, $ipv4) ]
        } ''',
    ''' /* A comment */ testint ''',
    ''' testint // a comment''',
    '''/* multi
         line */ testint ''',
    '''
        /* A
            multiline
            comment */
        [ inet:ipv4=1.2.3.4 ] // this is a comment
        // and this too...

        switch $foo {

            // The bar case...

            bar: {
                [ +#hehe.haha ]
            }

            /*
                The
                baz
                case
            */
            baz faz: {}
        } ''',
    '''
        inet:fqdn | graph
                    --degrees 2
                    --filter { -#nope }
                    --pivot { <- seen <- source }
                    --form-pivot inet:fqdn {<- * | limit 20}
                    --form-pivot inet:fqdn {-> * | limit 20}
                    --form-filter inet:fqdn {-inet:fqdn:issuffix=1}
                    --form-pivot syn:tag {-> *}
                    --form-pivot * {-> #} ''',
    '''
        for $foo in $foos {

            [ inet:ipv4=1.2.3.4 ]

            switch $foo {
                bar: { [ +#ohai ] break }
                baz: { [ +#visi ] continue }
            }

            [ inet:ipv4=5.6.7.8 ]
            [ +#hehe ]
        } ''',
]

# Generated with gen_parse_list below
_ParseResults = [
    'Query: []',
    'Query: [LiftTag: [TagName: foo]]',
    'Query: [CmdOper: [Const: help, Const: ()]]',
    'Query: [LiftProp: [Const: refs]]',
    'Query: [LiftTag: [TagVar: [Const: tag]]]',
    'Query: [LiftProp: [Const: wentto]]',
    'Query: [EditTagDel: [TagName: foo]]',
    'Query: [LiftProp: [Const: syn:tag]]',
    'Query: [LiftProp: [Const: teststr]]',
    'Query: [LiftProp: [Const: .created]]',
    'Query: [LiftTagTag: [TagName: baz.faz]]',
    'Query: [LiftProp: [Const: inet:fqdn]]',
    'Query: [LiftProp: [Const: inet:user]]',
    'Query: [LiftTag: [TagName: test.baz]]',
    'Query: [LiftTag: [TagName: hehe.haha]]',
    'Query: [LiftProp: [Const: inet:dns:a]]',
    'Query: [LiftPropBy: [Const: testint, Const: <, Const: 20]]',
    'Query: [LiftPropBy: [Const: testint, Const: >, Const: 20]]',
    'Query: [LiftPropBy: [Const: testint, Const: <, Const: 30]]',
    'Query: [LiftPropBy: [Const: testint, Const: >, Const: 30]]',
    'Query: [LiftPropBy: [Const: testint, Const: <=, Const: 20]]',
    'Query: [LiftPropBy: [Const: testint, Const: >=, Const: 20]]',
    'Query: [LiftPropBy: [Const: testint, Const: <=, Const: 30]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foo]]',
    'Query: [LiftFormTag: [Const: teststr, TagName: foo]]',
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, VarValue: [Const: foo]]]',
    'Query: [LiftPropBy: [Const: testint, Const: =, Const: 1234]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 20]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, VarValue: [Const: foo]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: ohmy]]',
    'Query: [LiftPropBy: [Const: .created, Const: <, Const: 2010]]',
    'Query: [LiftPropBy: [Const: .created, Const: >, Const: 2010]]',
    "Query: [CmdOper: [Const: iden, Const: ('deadb33f',)]]",
    'Query: [LiftProp: [Const: testcomp], PivotOut: []]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: =, Const: u]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 42]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: =, Const: ]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: u]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: =, Const: us]]',
    'Query: [LiftPropBy: [Const: teststr, Const: ~=, Const: zip]]',
    'Query: [LiftPropBy: [Const: .created, Const: =, Const: 2001]]',
    'Query: [LiftPropBy: [Const: .seen, Const: ~=, Const: ^r]]',
    'Query: [LiftPropBy: [Const: testint, Const: =, Const: 8675309]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 99999]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: ]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: 23]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: u]]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: us]]',
    'Query: [LiftProp: [Const: teststr], EditTagDel: [TagName: foo]]',
    'Query: [LiftFormTag: [Const: teststr, TagName: foo.bar]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: hello]]',
    'Query: [LiftProp: [Const: .seen], EditUnivDel: [UnivProp: .seen]]',
    'Query: [LiftPropBy: [Const: inet:ipv4:loc, Const: =, Const: us]]',
    'Query: [LiftPropBy: [Const: inet:ipv4:loc, Const: =, Const: zz]]',
    'Query: [LiftTag: [TagVar: [Const: tag]], EditTagDel: [TagVar: [Const: tag]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: ]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: u]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us]]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: us.]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: =, Const: us.v]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: bar], PivotIn: []]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: hehe]]',
    'Query: [LiftProp: [Const: teststr]]',
    'Query: [LiftProp: [Const: teststr], EditPropDel: [RelProp: tick]]',
    'Query: [LiftPropBy: [Const: file:bytes:size, Const: =, Const: 4]]',
    "Query: [CmdOper: [Const: movetag, Const: ('#a.b', '#a.m')]]",
    'Query: [LiftPropBy: [Const: pivcomp:tick, Const: =, VarValue: [Const: foo]]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: a.b], FiltOper: [Const: +, TagCond: [TagName: foo]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: ]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: 23]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us]]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: us.v]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: =, Const: us.va]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: bar], PivotIn: []]',
    'Query: [LiftFormTag: [Const: teststr, TagName: foo, Const: @=, Const: 2016]]',
    'Query: [LiftPropBy: [Const: teststr:tick, Const: =, Const: 2015]]',
    'Query: [LiftPropBy: [Const: inet:fqdn, Const: =, Const: woot.com]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, VarValue: [Const: foo]]]',
    'Query: [LiftProp: [Const: pivcomp], CmdOper: [Const: noderefs, Const: ()]]',
    'Query: [LiftProp: [Const: pivcomp], FormPivot: [AbsProp: testint]]',
    'Query: [LiftPropBy: [Const: testint, Const: =, Const: 3735928559]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us.v]]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: us.va]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foo], PivotInFrom: [AbsProp: has]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: visi], PivotToTags: [TagMatch: *]]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('1',)]]",
    "Query: [CmdOper: [Const: movetag, Const: ('#hehe', '#woot')]]",
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None]]',
    'Query: [LiftProp: [Const: testcomp], FormPivot: [AbsProp: testint]]',
    "Query: [LiftProp: [Const: testguid], CmdOper: [Const: max, Const: ('tick',)]]",
    "Query: [LiftProp: [Const: testguid], CmdOper: [Const: min, Const: ('tick',)]]",
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 3], EditPropSet: [RelProp: loc, Const: ]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.v]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us.va]]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: us.va.]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, AbsPropCond: [AbsProp: testint, Const: >, Const: 10]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, AbsPropCond: [AbsProp: testint, Const: <, Const: 30]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, TagValuCond: [TagName: foo, Const: @=, Const: 2016]]]',
    'Query: [LiftProp: [Const: teststr], EditTagAdd: [TagName: foo.bar]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foo], PivotInFrom: [AbsProp: has]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, Const: 2015]]]',
    'Query: [LiftPropBy: [Const: .created, Const: =, Const: {created}]]',
    'Query: [LiftProp: [Const: inet:ipv4], FormPivot: [AbsProp: teststr]]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('1',)]]",
    'Query: [EditNodeAdd: [AbsProp: pivcomp, List: None]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: foo.bar], PivotOut: []]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 12], EditPropSet: [RelProp: loc, Const: us]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va]]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: =, Const: us.va.sy]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, AbsPropCond: [AbsProp: testint, Const: >=, Const: 10]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, AbsPropCond: [AbsProp: testint, Const: <=, Const: 30]]]',
    'Query: [LiftProp: [Const: inet:dns:a], PropPivotOut: [RelProp: ipv4]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 10.2.1.1/28]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4]]',
    'Query: [EditNodeAdd: [AbsProp: pivcomp, List: None]]',
    "Query: [CmdOper: [Const: reindex, Const: ('--form-counts',)]]",
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: -, TagCond: [TagName: test]], PivotIn: []]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: -, TagCond: [TagName: test]], PivotOut: []]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.]]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: bar], EditTagAdd: [TagName: baz]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: foo], EditTagAdd: [TagName: bar]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foo], CmdOper: [Const: delnode, Const: ()]]',
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None], PivotOut: []]',
    'Query: [LiftPropBy: [Const: seen:source, Const: =, VarValue: [Const: sorc]], PivotOut: []]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: teststr, Const: foo]]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: -, TagCond: [TagName: test]], PivotIn: []]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: -, TagCond: [TagName: test]], PivotOut: []]',
    'Query: [LiftPropBy: [Const: testcomp:haha, Const: ~=, Const: ^lulz]]',
    'Query: [LiftPropBy: [Const: testcomp:haha, Const: ~=, Const: ^zerg]]',
    'Query: [LiftPropBy: [Const: testint, Const: =, Const: 123], CmdOper: [Const: noderefs, Const: ()]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us.va.sy]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: 123], CmdOper: [Const: noderefs, Const: ()]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foobar], FormPivot: [AbsProp: has]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: foo], EditTagAdd: [TagVar: [Const: tag]]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: haha], EditTagAdd: [TagName: foo]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: None]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: visi], PivotToTags: [TagMatch: baz.*]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: visi], PivotToTags: [TagMatch: foo.*]]',
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None], PivotOut: []]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: testguid, Const: *]]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: pivcomp]], PivotOut: []]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: teststr]], PivotIn: []]',
    'Query: [EditNodeAdd: [AbsProp: testcomp, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 10], EditPropSet: [RelProp: loc, Const: us.va]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: us.va.fair]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: =, Const: us.va.syria]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foo], FiltOper: [Const: +, TagValuCond: [TagName: lol, Const: @=, Const: 2014]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foo], FiltOper: [Const: +, TagValuCond: [TagName: lol, Const: @=, Const: 2016]]]',
    "Query: [LiftProp: [Const: teststr], CmdOper: [Const: noderefs, Const: ('-d', '3')]]",
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: woot.com]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 192.168.1.0/24]]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('--woot',)]]",
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: pivcomp]], PivotOut: []]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: teststr]], PivotIn: []]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: =, Const: us.va.sydney]]',
    'Query: [LiftFormTag: [Const: teststr, TagName: foo, Const: @=, List: None]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 1.2.3.1-1.2.3.3]]',
    "Query: [LiftProp: [Const: pivcomp], CmdOper: [Const: noderefs, Const: ('--join',)]]",
    'Query: [EditNodeAdd: [AbsProp: testguid, Const: *], EditPropSet: [RelProp: tick, Const: 2001]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.fair]]]',
    "Query: [LiftProp: [Const: teststr], CmdOper: [Const: delnode, Const: ('--force',)]]",
    'Query: [LiftPropBy: [Const: teststr:tick, Const: <, Const: 201808021202]]',
    'Query: [LiftPropBy: [Const: teststr:tick, Const: >, Const: 201808021202]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: woot], EditPropSet: [UnivProp: .seen, Const: 20]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, Const: 2012]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, Const: 2015]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, TagPropValue: [TagName: bar]]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, TagPropValue: [TagName: baz]]]]',
    "Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 1.2.3.4], CmdOper: [Const: limit, Const: ('20',)]]",
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: asn::name], Const: =, Const: visi]]]',
    "Query: [LiftProp: [Const: inet:ipv4], CmdOper: [Const: reindex, Const: ('--subs',)]]",
    'Query: [CmdOper: [Const: sudo, Const: ()], LiftPropBy: [Const: testint, Const: =, Const: 6], CmdOper: [Const: delnode, Const: ()]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: aaa.barbarella.ddd]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: foo.bar], FormPivot: [AbsProp: teststr]]',
    'Query: [EditNodeAdd: [AbsProp: testguid, Const: abcd], EditPropSet: [RelProp: tick, Const: 2015]]',
    "Query: [LiftPropBy: [Const: testint, Const: =, Const: 123], CmdOper: [Const: noderefs, Const: ('-te',)]]",
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 9], EditPropSet: [RelProp: loc, Const: us.ओं]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: us.va.fairfax]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us.va.sydney]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foo bar], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: teststr]]]',
    "Query: [LiftProp: [Const: teststr], CmdOper: [Const: noderefs, Const: ('-d', '3', '-u')]]",
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: None]]]',
    'Query: [LiftPropBy: [Const: teststr:tick, Const: <=, Const: 201808021202]]',
    'Query: [LiftPropBy: [Const: teststr:tick, Const: >=, Const: 201808021202]]',
    'Query: [LiftPropBy: [Const: .created, Const: *range=, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: inet:asn, Const: 200], EditPropSet: [RelProp: name, Const: visi]]',
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: woot.com], PivotOut: []]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.1-1.2.3.3]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 192.168.1.0/24]]',
    'Query: [LiftPropBy: [Const: pivtarg, Const: =, Const: hehe], EditPropSet: [UnivProp: .seen, Const: 2015]]',
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: has], PivotOut: []]',
    'Query: [EditNodeAdd: [AbsProp: testguid, Const: *], EditPropSet: [RelProp: tick, Const: 2015]]',
    'Query: [EditNodeAdd: [AbsProp: testguid, Const: *], EditPropSet: [RelProp: tick, Const: 2016]]',
    'Query: [EditNodeAdd: [AbsProp: testguid, Const: *], EditPropSet: [RelProp: tick, Const: 2017]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: us.va.fairfax.]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: bar], FormPivot: [AbsProp: pivcomp:lulz]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: beep], EditNodeAdd: [AbsProp: teststr, Const: boop]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, TagValuCond: [TagName: foo, Const: @=, List: None]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, TagValuCond: [TagName: foo, Const: @=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: foo], EditNodeAdd: [AbsProp: teststr, Const: bar]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: haha], EditTagAdd: [TagName: bar, Const: 2015]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: haha], EditTagAdd: [TagName: bar, Const: 2016]]',
    'Query: [LiftPropBy: [Const: .created, Const: *range=, List: None]]',
    'Query: [LiftPropBy: [Const: geo:place, Const: =, VarValue: [Const: place]], PivotInFrom: [AbsProp: has], PivotIn: []]',
    'Query: [LiftPropBy: [Const: inet:fqdn, Const: =, Const: woot.com], CmdOper: [Const: delnode, Const: ()]]',
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None], FormPivot: [AbsProp: pivtarg]]',
    'Query: [LiftPropBy: [Const: seen:source, Const: =, VarValue: [Const: sorc]], PropPivotOut: [RelProp: node]]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4]]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: teststr, Const: foo], EditTagAdd: [TagName: lol]]',
    'Query: [LiftProp: [Const: testcomp], PivotOut: [], CmdOper: [Const: uniq, Const: ()], CmdOper: [Const: count, Const: ()]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 1], EditPropSet: [RelProp: loc, Const: us.va.syria]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.fairfax]]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us.va. syria]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: bar], FormPivot: [AbsProp: pivcomp:lulz]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foo bar], EditPropDel: [RelProp: tick]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: hello], EditPropSet: [RelProp: tick, Const: 2001]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: hello], EditPropSet: [RelProp: tick, Const: 2002]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], EditPropSet: [RelProp: asn, Const: 20]]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('1',)]]",
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None], FormPivot: [AbsProp: pivtarg]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: baz.faz], EditTagAdd: [TagName: foo.bar]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 2], EditPropSet: [RelProp: loc, Const: us.va.sydney]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.fairfax.]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], EditPropSet: [RelProp: asn, Const: 200]]',
    "Query: [CmdOper: [Const: movetag, Const: ('#aaa.b', '#aaa.barbarella')]]",
    "Query: [LiftProp: [Const: pivcomp], CmdOper: [Const: noderefs, Const: ('--join', '-d', '3')]]",
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: wentto], PivotOut: []]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 4], EditPropSet: [RelProp: loc, Const: us.va.fairfax]]',
    'Query: [VarSetOper: [Const: bar, Const: 5.5.5.5], EditNodeAdd: [AbsProp: inet:ipv4, VarValue: [Const: bar]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, VarCall: [VarDeref: [VarValue: [Const: blob], Const: split], CallArgs: [Const: |]]]]',
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: -, AbsPropCond: [AbsProp: inet:ipv4, Const: =, Const: 1.2.3.0/30]]]',
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: +, AbsPropCond: [AbsProp: inet:ipv4, Const: =, Const: 1.2.3.0/30]]]',
    'Query: [EditNodeAdd: [AbsProp: pivcomp, List: None], EditPropSet: [RelProp: width, Const: 42]]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: teststr, Const: 123], EditPropSet: [RelProp: tick, Const: 2018]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: foo.bar], FormPivot: [AbsProp: teststr:tick]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 1], EditNodeAdd: [AbsProp: testint, Const: 2], EditNodeAdd: [AbsProp: testint, Const: 3]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 8], EditPropSet: [RelProp: loc, Const: us.ca.sandiego]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, TagValuCond: [TagName: foo, Const: @=, List: None]]]',
    'Query: [LiftProp: [Const: teststr], EditTagAdd: [TagName: foo.bar, List: None]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foo bar], FiltOper: [Const: -, HasAbsPropCond: [AbsProp: teststr:tick]]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: foo bar], EditPropSet: [RelProp: tick, Const: 2018]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, List: None]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: visi], EditTagAdd: [TagName: foo.bar], PivotToTags: [TagMatch: ]]',
    'Query: [LiftPropBy: [Const: inet:fqdn, Const: =, Const: woot.com], FormPivot: [AbsProp: inet:dns:a]]',
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: +, AbsPropCond: [AbsProp: inet:ipv4, Const: =, Const: 10.2.1.4/31]]]',
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: +, AbsPropCond: [AbsProp: inet:ipv4, Const: =, Const: 10.2.1.4/32]]]',
    'Query: [EditNodeAdd: [AbsProp: pivcomp, List: None], EditPropSet: [RelProp: tick, Const: 2018]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: foobar], FormPivot: [AbsProp: has], PivotInFrom: [AbsProp: teststr]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: foo], EditPropSet: [RelProp: tick, Const: 201808021201]]',
    "Query: [LiftProp: [Const: teststr], CmdOper: [Const: noderefs, Const: ('-d', '3', '--unique')]]",
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: None]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, List: None]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: None]]',
    "Query: [LiftProp: [Const: pivcomp], CmdOper: [Const: noderefs, Const: ('-j', '--degrees', '2')]]",
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: cycle0, Const: foo], EditPropSet: [RelProp: cycle1, Const: bar]]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: cycle1, Const: bar], EditPropSet: [RelProp: cycle0, Const: foo]]',
    'Query: [LiftProp: [Const: testcomp], FiltOper: [Const: +, OrCond: [RelPropCond: [RelPropValue: [RelProp: hehe], Const: <, Const: 2], RelPropCond: [RelPropValue: [RelProp: haha], Const: =, Const: foob]]]]',
    'Query: [LiftProp: [Const: testcomp], FiltOper: [Const: +, OrCond: [RelPropCond: [RelPropValue: [RelProp: hehe], Const: <, Const: 2], RelPropCond: [RelPropValue: [RelProp: haha], Const: =, Const: test]]]]',
    'Query: [LiftProp: [Const: testcomp], FiltOper: [Const: +, OrCond: [RelPropCond: [RelPropValue: [RelProp: hehe], Const: <, Const: 2], TagCond: [TagName: meep.gorp]]]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: us.va.fairfax.reston]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: abcd], EditPropSet: [RelProp: tick, Const: 2015], EditTagAdd: [TagName: cool], LiftPropBy: [Const: teststr, Const: =, Const: foobar], FormPivot: [AbsProp: has], PivotInFrom: [AbsProp: teststr]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3')]]",
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: None]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, List: None]]]',
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None], PropPivot: [RelPropValue: [RelProp: lulz], AbsProp: teststr]]',
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None], PropPivot: [RelPropValue: [RelProp: targ], AbsProp: pivtarg]]',
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: wentto], PropPivotOut: [RelProp: n2]]',
    'Query: [LiftProp: [Const: testcomp], FiltOper: [Const: +, AndCond: [RelPropCond: [RelPropValue: [RelProp: hehe], Const: <, Const: 2], RelPropCond: [RelPropValue: [RelProp: haha], Const: =, Const: foob]]]]',
    'Query: [LiftProp: [Const: testcomp], FiltOper: [Const: +, AndCond: [RelPropCond: [RelPropValue: [RelProp: hehe], Const: <, Const: 2], RelPropCond: [RelPropValue: [RelProp: haha], Const: =, Const: test]]]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: foo], EditTagAdd: [TagName: bar], FiltOper: [Const: +, NotCond: [HasRelPropCond: [UnivProp: .seen]]]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: foo], EditNodeAdd: [AbsProp: teststr, Const: bar], CmdOper: [Const: spin, Const: ()]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: hehe], EditTagAdd: [TagName: foo, List: None]]',
    "Query: [EditNodeAdd: [AbsProp: teststr, Const: hehe], CmdOper: [Const: iden, Const: ('abcd',)], CmdOper: [Const: count, Const: ()]]",
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, AbsPropCond: [AbsProp: teststr:tick, Const: <, Const: 201808021202]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, AbsPropCond: [AbsProp: teststr:tick, Const: >, Const: 201808021202]]]',
    'Query: [LiftPropBy: [Const: teststr:tick, Const: =, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: woot], EditTagAdd: [TagName: foo, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: woot], EditPropSet: [UnivProp: .seen, List: None]]',
    "Query: [LiftPropBy: [Const: cluster, Const: =, Const: abcd], CmdOper: [Const: noderefs, Const: ('-d', '2', '--join')]]",
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None], PropPivot: [RelPropValue: [RelProp: lulz], AbsProp: teststr]]',
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: has], FormPivot: [AbsProp: geo:place]]',
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: has], FormPivot: [AbsProp: inet:ipv4]]',
    'Query: [EditNodeAdd: [AbsProp: seen, List: None]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.fairfax.reston]]]',
    'Query: [LiftProp: [Const: teststr], EditTagAdd: [TagName: foo.bar, List: None]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, AbsPropCond: [AbsProp: teststr:tick, Const: <=, Const: 201808021202]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, AbsPropCond: [AbsProp: teststr:tick, Const: >=, Const: 201808021202]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, List: None]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, List: None]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: woot], VarSetOper: [Const: foo, TagPropValue: [TagName: foo]], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, VarValue: [Const: foo]]]]',
    'Query: [LiftPropBy: [Const: geo:place:latlong, Const: *near=, List: None]]',
    'Query: [LiftPropBy: [Const: geo:place, Const: =, VarValue: [Const: place]], PivotInFrom: [AbsProp: has], PivotInFrom: [AbsProp: inet:ipv4]]',
    'Query: [LiftPropBy: [Const: geo:place, Const: =, VarValue: [Const: place]], PivotInFrom: [AbsProp: has], PivotInFrom: [AbsProp: ps:person]]',
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: +, AbsPropCond: [AbsProp: inet:ipv4, Const: =, Const: 1.2.3.1-1.2.3.3]]]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('10',)], EditTagAdd: [TagName: foo.bar]]",
    'Query: [EditNodeAdd: [AbsProp: inet:user, Const: visi], EditNodeAdd: [AbsProp: inet:user, Const: whippit]]',
    'Query: [LiftPropBy: [Const: testint:loc, Const: ^=, Const: us.va.fairfax.chantilly]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, List: None]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: None]]]',
    "Query: [CmdOper: [Const: iden, Const: ('2cdd997872b10a65407ad5fadfa28e0d',)]]",
    "Query: [LiftProp: [Const: pivcomp], CmdOper: [Const: noderefs, Const: ('--join', '--degrees', '2')]]",
    'Query: [LiftProp: [Const: testguid], FiltOper: [Const: +, AbsPropCond: [AbsProp: testguid, Const: *range=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 5], EditPropSet: [RelProp: loc, Const: us.va.fairfax.reston]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: visi], EditNodeAdd: [AbsProp: testint, Const: 20], EditTagAdd: [TagName: foo.bar]]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('10',)], FiltOper: [Const: +, AbsPropCond: [AbsProp: inet:user, Const: =, Const: visi]]]",
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: wentto], FormPivot: [AbsProp: inet:ipv4]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 7], EditPropSet: [RelProp: loc, Const: us.va.fairfax.herndon]]',
    'Query: [LiftProp: [Const: testint], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.fairfax.chantilly]]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: 123], CmdOper: [Const: noderefs, Const: ('--traverse-edge',)]]",
    "Query: [EditNodeAdd: [AbsProp: teststr, Const: foo], EditNodeAdd: [AbsProp: teststr, Const: bar], CmdOper: [Const: sleep, Const: ('10',)]]",
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: foo], EditNodeAdd: [AbsProp: teststr, Const: bar], EditNodeAdd: [AbsProp: testint, Const: 42]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:query, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 94.75.194.194], EditPropSet: [RelProp: loc, Const: nl]]',
    'Query: [EditNodeAdd: [AbsProp: refs, List: None]]',
    'Query: [LiftPropBy: [Const: source, Const: =, Const: 8f1401de15918358d5247e21ca29a814]]',
    'Query: [LiftProp: [Const: testcomp], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: haha], Const: *range=, List: None]]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: 123], EditPropSet: [RelProp: baz, Const: testguid:tick=2015]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: geo:place, Const: *], EditPropSet: [RelProp: latlong, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: woot.com], EditTagAdd: [TagName: bad, List: None]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: 1234], LiftPropBy: [Const: teststr, Const: =, Const: duck], LiftPropBy: [Const: teststr, Const: =, Const: knight]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('--join', '-d', '9')]]",
    'Query: [EditNodeAdd: [AbsProp: has, List: None]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: None], VarSetOper: [Const: newp, UnivPropValue: [UnivProp: .seen]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: None], EditTagAdd: [TagName: yepr]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: foo], EditTagAdd: [TagName: bar], SubQuery: [Query: [EditTagAdd: [TagName: baz], FiltOper: [Const: -, TagCond: [TagName: bar]]]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: None]]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: *range=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.0/30], EditNodeAdd: [AbsProp: inet:ipv4, Const: 5.5.5.5]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: bar], LiftPropBy: [Const: pivcomp, Const: =, List: None], EditTagAdd: [TagName: test.bar]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: foo], EditTagAdd: [TagName: bar], FiltOper: [Const: +, OrCond: [TagCond: [TagName: baz], NotCond: [HasRelPropCond: [UnivProp: .seen]]]]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '-ot=omit')]]",
    'Query: [ForLoop: [Const: fqdn, Const: fqdns, SubQuery: [Query: [EditNodeAdd: [AbsProp: inet:fqdn, VarValue: [Const: fqdn]]]]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: -, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], FiltOper: [Const: -, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us]]]]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: -, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us]]]]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: +, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], FiltOper: [Const: -, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us]]]]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: +, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us]]]]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: vertex.link], EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 1.2.3.4], FiltOper: [Const: +, SubqCond: [Query: [FormPivot: [AbsProp: inet:dns:a]], Const: <=, Const: 1]]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 1.2.3.4], FiltOper: [Const: +, SubqCond: [Query: [FormPivot: [AbsProp: inet:dns:a]], Const: >=, Const: 3]]]',
    'Query: [EditNodeAdd: [AbsProp: testcomp, List: None], EditTagAdd: [TagName: foo.bar], EditTagDel: [TagName: foo.bar]]',
    'Query: [LiftPropBy: [Const: teststr, Const: =, Const: a], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: *range=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: None], EditTagAdd: [TagName: nope]]',
    'Query: [EditNodeAdd: [AbsProp: testcomp, List: None], EditNodeAdd: [AbsProp: testcomp, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: testint, Const: 6], EditPropSet: [RelProp: loc, Const: us.va.fairfax.restonheights]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: a], SwitchCase: [VarValue: [Const: woot], CaseEntry: [Const: hehe, SubQuery: [Query: [EditTagAdd: [TagName: baz]]]]]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '-of=source')]]",
    'Query: [LiftPropBy: [Const: geo:place:latlong, Const: *near=, List: None]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: +, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], FiltOper: [Const: -, RelPropCond: [RelPropValue: [RelProp: asn], Const: =, Const: 1234]]]]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: +, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: asn], Const: =, Const: 1234]]]]]]',
    'Query: [LiftPropBy: [Const: inet:fqdn, Const: =, Const: woot.com], FormPivot: [AbsProp: inet:dns:a], FormPivot: [AbsProp: inet:ipv4]]',
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None], FiltOper: [Const: -, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: lulz], AbsProp: teststr], FiltOper: [Const: +, TagCond: [TagName: baz]]]]]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '-otf=source')]]",
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: visi], EditTagAdd: [TagName: foo.bar], PivotToTags: [TagMatch: ], EditTagAdd: [TagName: baz.faz]]',
    'Query: [LiftProp: [Const: geo:place], FiltOper: [Const: -, RelPropCond: [RelPropValue: [RelProp: latlong], Const: *near=, List: None]]]',
    "Query: [LiftPropBy: [Const: inet:asn, Const: =, Const: 10], CmdOper: [Const: noderefs, Const: ('-of', 'inet:ipv4', '--join', '-d', '3')]]",
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: bar], Const: *range=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: oof], EditTagAdd: [TagName: bar], SubQuery: [Query: [EditNodeAdd: [AbsProp: testint, Const: 0xdeadbeef]]]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 12.34.56.78], EditPropSet: [RelProp: loc, Const: us.oh.wilmington]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '--omit-tag=omit')]]",
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: None], EditPropSet: [UnivProp: .seen, List: None]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: None], EditPropSet: [UnivProp: .seen, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:query, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: pivcomp, List: None], EditPropSet: [RelProp: tick, Const: 2015], EditTagAdd: [TagName: foo, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: refs, List: None]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '--omit-form=source')]]",
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: woot], EditTagAdd: [TagName: foo, List: None], EditPropSet: [UnivProp: .seen, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: testcomp, List: None], EditTagAdd: [TagName: meep.gorp], EditTagAdd: [TagName: bleep.zlorp], EditTagAdd: [TagName: cond]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: None], VarSetOper: [Const: hehe, RelPropValue: [RelProp: fqdn]], FiltOper: [Const: -, RelPropCond: [RelPropValue: [RelProp: fqdn], Const: =, VarValue: [Const: hehe]]]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: None], VarSetOper: [Const: hehe, RelPropValue: [RelProp: fqdn]], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: fqdn], Const: =, VarValue: [Const: hehe]]]]',
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None], FiltOper: [Const: +, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: lulz], AbsProp: teststr], FiltOper: [Const: +, TagCond: [TagName: baz]]]]], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: pivcomp]]]',
    'Query: [LiftProp: [Const: geo:place], FiltOper: [Const: +, AbsPropCond: [AbsProp: geo:place:latlong, Const: *near=, List: None]]]',
    'Query: [LiftPropBy: [Const: inet:dns:query, Const: =, List: None], PropPivot: [RelPropValue: [RelProp: name], AbsProp: inet:fqdn]]',
    'Query: [EditNodeAdd: [AbsProp: source, Const: abcd], EditTagAdd: [TagName: omit.nopiv], EditNodeAdd: [AbsProp: seen, List: None]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('--join', '-d', '9', '--traverse-edge')]]",
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: None], VarSetOper: [Const: hehe, RelPropValue: [RelProp: fqdn]], LiftPropBy: [Const: inet:fqdn, Const: =, VarValue: [Const: hehe]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], EditPropSet: [RelProp: asn, Const: 10], EditNodeAdd: [AbsProp: seen, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: c], SwitchCase: [VarValue: [Const: woot], CaseEntry: [Const: hehe, SubQuery: [Query: [EditTagAdd: [TagName: baz]]]], CaseEntry: [SubQuery: [Query: [EditTagAdd: [TagName: jaz]]]]]]',
    'Query: [LiftPropBy: [Const: geo:place:latlong, Const: *near=, List: None]]',
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: wentto], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: time], Const: @=, List: None]], FormPivot: [AbsProp: geo:place]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: woot], EditTagAdd: [TagName: foo, List: None], EditTagAdd: [TagName: bar], EditPropSet: [UnivProp: .seen, List: None]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '-ott=omit.nopiv', '-ott=test')]]",
    "Query: [ForLoop: [VarList: ['fqdn', 'ipv4'], Const: dnsa, SubQuery: [Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: None]]]]]",
    'Query: [LiftPropBy: [Const: geo:place:latlong, Const: *near=, List: None]]',
    'Query: [LiftProp: [Const: testcomp], FiltOper: [Const: +, AbsPropCond: [AbsProp: testcomp, Const: *range=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], EditPropSet: [RelProp: loc, Const: us], EditNodeAdd: [AbsProp: inet:dns:a, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 4.3.2.1], EditPropSet: [RelProp: loc, Const: zz], EditNodeAdd: [AbsProp: inet:dns:a, List: None]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '--omit-traversal-form=source')]]",
    'Query: [LiftPropBy: [Const: pivcomp, Const: =, List: None], VarSetOper: [Const: ticktock, TagPropValue: [TagName: foo]], FormPivot: [AbsProp: pivtarg], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, VarValue: [Const: ticktock]]]]',
    "Query: [EditNodeAdd: [AbsProp: testcomp, List: None], EditNodeAdd: [AbsProp: testcomp, List: None], EditNodeAdd: [AbsProp: testcomp, List: None], ForLoop: [VarList: ['fqdn', 'ipv4', 'boom'], Const: dnsa, SubQuery: [Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: None]]]]]",
    'Query: [LiftProp: [Const: inet:fqdn], FiltOper: [Const: +, TagCond: [TagName: bad]], VarSetOper: [Const: fqdnbad, TagPropValue: [TagName: bad]], FormPivot: [AbsProp: inet:dns:a:fqdn], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, VarValue: [Const: fqdnbad]]]]',
    'Query: [LiftPropBy: [Const: media:news, Const: =, Const: 00a1f0d928e25729b9e86e2d08c127ce], EditPropSet: [RelProp: summary, Const: ]]',
    'Query: [EditNodeAdd: [AbsProp: refs, List: None]]',
    'Query: [LiftProp: [Const: teststr], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: .seen], Const: *range=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: None], EditNodeAdd: [AbsProp: inet:dns:a, List: None]]',
    'Query: [LiftProp: [Const: refs], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: n1], Const: *range=, List: None]]]',
    'Query: [LiftPropBy: [Const: inet:dns:query, Const: =, List: None], PropPivot: [RelPropValue: [RelProp: name], AbsProp: inet:fqdn]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: None], EditPropSet: [UnivProp: .seen, List: None]]',
    'Query: [LiftProp: [Const: testint], CmdOper: [Const: noderefs, Const: ()], FiltOper: [Const: +, AbsPropCond: [AbsProp: testcomp, Const: *range=, List: None]]]',
    'Query: [EditNodeAdd: [AbsProp: refs, List: None]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: None], VarSetOper: [Const: seen, UnivPropValue: [UnivProp: .seen]], PropPivot: [RelPropValue: [RelProp: fqdn], AbsProp: inet:fqdn], EditPropSet: [UnivProp: .seen, VarValue: [Const: seen]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: woot.com], EditNodeAdd: [AbsProp: inet:fqdn, Const: vertex.link], EditNodeAdd: [AbsProp: inet:user, RelPropValue: [RelProp: zone]], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: inet:user]]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: None], EditPropSet: [UnivProp: .seen, List: None]]',
    'Query: [EditNodeAdd: [AbsProp: teststr, Const: c], SwitchCase: [VarValue: [Const: woot], CaseEntry: [Const: hehe, SubQuery: [Query: [EditTagAdd: [TagName: baz]]]], CaseEntry: [Const: haha hoho, SubQuery: [Query: [EditTagAdd: [TagName: faz]]]], CaseEntry: [Const: lolz:lulz, SubQuery: [Query: [EditTagAdd: [TagName: jaz]]]]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: hehe.com], EditNodeAdd: [AbsProp: inet:ipv4, Const: 127.0.0.1], EditNodeAdd: [AbsProp: hash:md5, Const: d41d8cd98f00b204e9800998ecf8427e]]',
    "Query: [LiftPropBy: [Const: teststr, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '--omit-traversal-tag=omit.nopiv', '--omit-traversal-tag=test')]]",
    'Query: [LiftPropBy: [Const: geo:place, Const: =, Const: abcd], VarSetOper: [Const: latlong, RelPropValue: [RelProp: latlong]], VarSetOper: [Const: radius, RelPropValue: [RelProp: radius]], CmdOper: [Const: spin, Const: ()], LiftPropBy: [Const: tel:mob:telem:latlong, Const: *near=, List: None]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 12.34.56.78], LiftPropBy: [Const: inet:fqdn, Const: =, Const: woot.com], EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], EditPropSet: [RelProp: asn, Const: 10101], EditNodeAdd: [AbsProp: inet:fqdn, Const: woowoo.com], EditTagAdd: [TagName: my.tag]]',
    "Query: [ForLoop: [Const: foo, Const: foos, SubQuery: [Query: [VarListSetOper: [VarList: ['fqdn', 'ipv4'], VarCall: [VarDeref: [VarValue: [Const: foo], Const: split], CallArgs: [Const: |]]], EditNodeAdd: [AbsProp: inet:dns:a, List: None]]]]]",
    'Query: [LiftProp: [Const: testint]]',
    'Query: [LiftProp: [Const: testint]]',
    'Query: [LiftProp: [Const: testint]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], SwitchCase: [VarValue: [Const: foo], CaseEntry: [Const: bar, SubQuery: [Query: [EditTagAdd: [TagName: hehe.haha]]]], CaseEntry: [Const: baz faz, SubQuery: [Query: []]]]]',
    "Query: [LiftProp: [Const: inet:fqdn], CmdOper: [Const: graph, Const: ('--degrees', '2', '--filter', '{ -#nope }', '--pivot', '{ <- seen <- source }', '--form-pivot', 'inet:fqdn', '{<- * | limit 20}', '--form-pivot', 'inet:fqdn', '{-> * | limit 20}', '--form-filter', 'inet:fqdn', '{-inet:fqdn:issuffix=1}', '--form-pivot', 'syn:tag', '{-> *}', '--form-pivot', '*', '{-> #}')]]",
    'Query: [ForLoop: [Const: foo, Const: foos, SubQuery: [Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], SwitchCase: [VarValue: [Const: foo], CaseEntry: [Const: bar, SubQuery: [Query: [EditTagAdd: [TagName: ohai], BreakOper: []]]], CaseEntry: [Const: baz, SubQuery: [Query: [EditTagAdd: [TagName: visi], ContinueOper: []]]]], EditNodeAdd: [AbsProp: inet:ipv4, Const: 5.6.7.8], EditTagAdd: [TagName: hehe]]]]]']

class GrammarTest(s_t_utils.SynTest):

    def test_grammar(self):
        grammar = open('synapse/lib/storm.g').read()

        parser = lark.Lark(grammar, start='query', debug=True)

        for i, query in enumerate(_Queries):
            try:

                parser.parse(query)
                # print(f'{tree.pretty()}\n)')
            except (lark.ParseError, lark.UnexpectedCharacters):
                # print(f'Failure on parsing {{{query}}}')
                raise

    async def test_parser(self):
        async with self.getTestCore() as core:

            parseinfo = {
                'stormcmds': {cmd: {} for cmd in core.stormcmds.keys()},
                'modelinfo': core.model.getModelInfo(),
            }
            for i, query in enumerate(_Queries):
                print(f'{{{query}}}')
                if i > 10:
                    # FIXME:  increase as we get more
                    break
                parser = s_syntax2.Parser(parseinfo, query)
                tree = parser.query()
                self.eq(str(tree), _ParseResults[i])

def gen_parse_list():
    import synapse.lib.syntax as s_syntax
    import synapse.lib.coro as s_coro

    t = s_t_utils.SynTest()
    with s_coro.AsyncToSyncCMgr(t.getTestCore) as core:
        parseinfo = {
            'stormcmds': {cmd: {} for cmd in core.stormcmds.keys()},
            'modelinfo': core.model.getModelInfo(),
        }
        retn = []
        for i, query in enumerate(_Queries):
            parser = s_syntax.Parser(parseinfo, query)
            tree = parser.query()
            retn.append(str(tree))
    return retn
