import synapse.lib.syntax2 as s_syntax2

import synapse.tests.utils as s_t_utils
import lark

_Queries = [
    '',
    '#foo',
    'help',
    'edge:refs',
    '#$tag',
    'edge:wentto',
    '[-#foo]',
    'syn:tag',
    'test:str',
    '.created',
    '##baz.faz',
    'inet:fqdn',
    'inet:user',
    '#test.baz',
    '#hehe.haha',
    'inet:dns:a',
    'test:int<20',
    'test:int>20',
    'test:int<30',
    'test:int>30',
    'test:int <=20',
    'test:int>=20',
    'test:int<=30',
    'test:str=foo',
    'test:str#foo',
    'test:pivcomp=$foo',
    'test:int=1234',
    '[test:int=20]',
    'test:str=$foo',
    'test:str=ohmy',
    '.created<2010',
    '.created>2010',
    'iden deadb33f',
    'test:comp -> *',
    'test:int:loc=u',
    '[ test:int=42 ]',
    'test:int:loc=""',
    'test:int:loc^=u',
    'test:int:loc=us',
    'test:str~="zip"',
    '.created="2001"',
    '.seen~="^r"',
    'test:int=8675309',
    '[test:int=99999]',
    'test:int:loc^=""',
    'test:int:loc^=23',
    'test:int +:loc=u',
    'test:int:loc^=us',
    'test:str [-#foo]',
    'test:str#foo.bar',
    '[test:str=hello]',
    '.seen [ -.seen ]',
    'inet:ipv4:loc=us',
    'inet:ipv4:loc=zz',
    '#$tag [ -#$tag ]',
    'test:int +:loc=""',
    'test:int +:loc^=u',
    'test:int +:loc=us',
    'test:int:loc^=us.',
    'test:int:loc=us.v',
    'test:str=bar <- *',
    '[ test:str=hehe ]',
    'test:str [-:tick]',
    'file:bytes:size=4',
    'movetag #a.b #a.m',
    'test:pivcomp:tick=$foo',
    'syn:tag=a.b +#foo',
    'test:int +:loc^=""',
    'test:int +:loc^=23',
    'test:int +:loc^=us',
    'test:int:loc^=us.v',
    'test:int:loc=us.va',
    'test:str=bar <+- *',
    'test:str#foo@=2016',
    'test:str:tick=2015',
    'inet:fqdn=woot.com',
    '[ inet:ipv4=$foo ]',
    'test:pivcomp | noderefs',
    'test:pivcomp -> test:int',
    'test:int=3735928559',
    'test:int +:loc^=us.',
    'test:int +:loc=us.v',
    'test:int:loc^=us.va',
    'test:str=foo <- edge:has',
    'test:str=visi -> #*',
    'inet:user | limit 1',
    'movetag #hehe #woot',
    'test:pivcomp=(hehe,haha)',
    'test:comp -> test:int',
    'test:guid | max tick',
    'test:guid | min tick',
    '[test:int=3 :loc=""]',
    'test:int +:loc^=us.v',
    'test:int +:loc=us.va',
    'test:int:loc^=us.va.',
    'test:int +test:int>10',
    'test:int +test:int<30',
    'test:str +#foo@=2016',
    'test:str [+#foo.bar]',
    'test:str=foo <+- edge:has',
    'test:str +:tick=2015',
    '.created="{created}"',
    'inet:ipv4 -> test:str',
    'inet:user | limit 1',
    '[test:pivcomp=(foo, 123)]',
    'syn:tag=foo.bar -> *',
    '[test:int=12 :loc=us]',
    'test:int +:loc^=us.va',
    'test:int:loc=us.va.sy',
    'test:int +test:int>=10',
    'test:int +test:int<=30',
    'inet:dns:a :ipv4 -> *',
    'inet:ipv4=10.2.1.1/28',
    '[ inet:ipv4=1.2.3.4 ]',
    '[ test:pivcomp=(foo,bar) ]',
    'reindex --form-counts',
    '#test.bar -#test <- *',
    '#test.bar -#test -> *',
    'test:int +:loc^=us.va.',
    '[ test:str=bar +#baz ]',
    '[ test:str=foo +#bar ]',
    'test:str=foo | delnode',
    'test:pivcomp=(foo,bar) -> *',
    'meta:seen:meta:source=$sorc -> *',
    'sudo | [ test:str=foo ]',
    '#test.bar -#test <+- *',
    '#test.bar -#test -+> *',
    'test:comp:haha~="^lulz"',
    'test:comp:haha~="^zerg"',
    'test:int=123 | noderefs',
    'test:int +:loc=us.va.sy',
    'test:str=123 | noderefs',
    'test:str=foobar -+> edge:has',
    '[ test:str=foo +#$tag ]',
    '[ test:str=haha +#foo ]',
    'test:str +:tick@=(2015)',
    'test:str=visi -> #baz.*',
    'test:str=visi -> #foo.*',
    'test:pivcomp=(foo,bar) -+> *',
    'sudo | [ test:guid="*" ]',
    '#test.bar +test:pivcomp -> *',
    '#test.bar +test:str <- *',
    '[test:comp=(1234, 5678)]',
    '[test:int=10 :loc=us.va]',
    'test:int:loc^=us.va.fair',
    'test:int:loc=us.va.syria',
    'test:str=foo +#lol@=2014',
    'test:str=foo +#lol@=2016',
    'test:str | noderefs -d 3',
    '[ inet:fqdn = woot.com ]',
    'inet:ipv4=192.168.1.0/24',
    'inet:user | limit --woot',
    '#test.bar +test:pivcomp -+> *',
    '#test.bar +test:str <+- *',
    'test:int:loc=us.va.sydney',
    'test:str#foo@=(2012,2022)',
    'inet:ipv4=1.2.3.1-1.2.3.3',
    'test:pivcomp | noderefs --join',
    '[test:guid="*" :tick=2001]',
    'test:int +:loc^=us.va.fair',
    'test:str | delnode --force',
    'test:str:tick<201808021202',
    'test:str:tick>201808021202',
    '[ test:str=woot .seen=20 ]',
    'test:str=woot +.seen@=2012',
    'test:str=woot +.seen@=2015',  # delete
    'test:str=woot +.seen@=#bar',
    'test:str=woot +.seen@=#baz',  # delete
    'inet:ipv4=1.2.3.4|limit 20',
    'inet:ipv4 +:asn::name=visi',
    'inet:ipv4 | reindex --subs',
    'sudo | test:int=6 | delnode',
    'syn:tag=aaa.barbarella.ddd',
    'syn:tag=foo.bar -> test:str',
    '[test:guid=abcd :tick=2015]',
    'test:int=123 | noderefs -te',
    '[test:int=9 :loc=us.ओं]',
    'test:int:loc^=us.va.fairfax',
    'test:int +:loc=us.va.sydney',
    'test:str="foo bar" +test:str',
    'test:str | noderefs -d 3 -u',
    'test:str +:tick@=("-1 day")',
    'test:str:tick<=201808021202',
    'test:str:tick>=201808021202',
    '.created*range=(2010, 3001)',
    '[ inet:asn=200 :name=visi ]',
    '[ inet:fqdn=woot.com ] -> *',
    '[inet:ipv4=1.2.3.1-1.2.3.3]',
    '[ inet:ipv4=192.168.1.0/24]',
    'test:pivtarg=hehe [ .seen=2015 ]',
    'ps:person=$pers -> edge:has -> *',
    '[ test:guid="*" :tick=2015 ]',
    '[ test:guid="*" :tick=2016 ]',
    '[ test:guid="*" :tick=2017 ]',
    'test:int:loc^=us.va.fairfax.',
    'test:str=bar -> test:pivcomp:lulz',
    '[test:str=beep test:str=boop]',
    'test:str +#foo@=(2014, 2019)',
    'test:str +#foo@=(2015, 2018)',
    '[ test:str=foo test:str=bar ]',
    '[ test:str=haha +#bar=2015 ]',
    '[ test:str=haha +#bar=2016 ]',
    '.created*range=("2010", "?")',
    'geo:place=$place <- edge:has <- *',
    'inet:fqdn=woot.com | delnode',
    'test:pivcomp=(foo,bar) -> test:pivtarg',
    'meta:seen:meta:source=$sorc :node -> *',
    'sudo | [ inet:ipv4=1.2.3.4 ]',
    'sudo | [ test:str=foo +#lol ]',
    'test:comp -> * | uniq | count',
    '[test:int=1 :loc=us.va.syria]',
    'test:int +:loc^=us.va.fairfax',
    'test:int +:loc="us.va. syria"',
    'test:str=bar -+> test:pivcomp:lulz',
    'test:str="foo bar" [ -:tick ]',
    'test:str=hello [:tick="2001"]',
    'test:str=hello [:tick="2002"]',
    '[ inet:ipv4=1.2.3.4 :asn=20 ]',
    'test:pivcomp=(foo,bar) -+> test:pivtarg',
    'syn:tag=baz.faz [ +#foo.bar ]',
    '[test:int=2 :loc=us.va.sydney]',
    'test:int +:loc^=us.va.fairfax.',
    '[ inet:ipv4=1.2.3.4 :asn=200 ]',
    'movetag #aaa.b #aaa.barbarella',
    'test:pivcomp | noderefs --join -d 3',
    'ps:person=$pers -> edge:wentto -> *',
    '[test:int=4 :loc=us.va.fairfax]',
    '$bar=5.5.5.5 [ inet:ipv4=$bar ]',
    '[ inet:dns:a=$blob.split("|") ]',
    'inet:ipv4 -inet:ipv4=1.2.3.0/30',
    'inet:ipv4 +inet:ipv4=1.2.3.0/30',
    '[ test:pivcomp=(xxx,yyy) :width=42 ]',
    'sudo | [test:str=123 :tick=2018]',
    'syn:tag=foo.bar -> test:str:tick',
    '[test:int=1 test:int=2 test:int=3]',
    '[test:int=8 :loc=us.ca.sandiego]',
    'test:str +#foo@=(2014, 20141231)',
    'test:str [+#foo.bar=(2000,2002)]',
    'test:str="foo bar" -test:str:tick',
    '[ test:str="foo bar" :tick=2018]',
    'test:str +:tick=(2015, "+1 day")',
    'test:str +:tick@=(now, "-1 day")',
    '[ test:str=visi +#foo.bar ] -> #',
    'inet:fqdn=woot.com -> inet:dns:a',
    'inet:ipv4 +inet:ipv4=10.2.1.4/31',
    'inet:ipv4 +inet:ipv4=10.2.1.4/32',
    '[ test:pivcomp=(foo,bar) :tick=2018 ]',
    'test:str=foobar -> edge:has <- test:str',
    '[test:str=foo :tick=201808021201]',
    'test:str | noderefs -d 3 --unique',
    'test:str +:tick@=(2015, "+1 day")',
    'test:str=woot +.seen@=(2012,2013)',
    'test:str=woot +.seen@=(2012,2015)',
    '[ inet:dns:a=(woot.com,1.2.3.4) ]',
    'test:pivcomp | noderefs -j --degrees 2',
    'sudo | [ test:cycle0=foo :test:cycle1=bar ]',
    'sudo | [ test:cycle1=bar :test:cycle0=foo ]',
    'test:comp +(:hehe<2 or :haha=foob)',
    'test:comp +(:hehe<2 or :haha=test)',
    'test:comp +(:hehe<2 or #meep.gorp)',
    'test:int:loc^=us.va.fairfax.reston',
    "[ test:str=abcd :tick=2015 +#cool ]"
    'test:str=foobar -> edge:has <+- test:str',
    'test:str=pennywise | noderefs -d 3',
    'test:str +:tick@=("now-1day", "?")',
    'test:str +:tick=($test, "+- 2day")',
    'test:pivcomp=(foo,bar) :lulz -> test:str',
    'test:pivcomp=(foo,bar) :targ -> test:pivtarg',
    'ps:person=$pers -> edge:wentto :n2 -> *',
    'test:comp +(:hehe<2 and :haha=foob)',
    'test:comp +(:hehe<2 and :haha=test)',
    '[ test:str=foo +#bar ] +(not .seen)',
    '[ test:str=foo test:str=bar ] | spin',
    '[ test:str=hehe +#foo=(2014,2016) ]',
    '[test:str=hehe] | iden abcd | count',
    'test:str +test:str:tick<201808021202',
    'test:str +test:str:tick>201808021202',
    'test:str:tick=(20131231, "+2 days")',
    '[ test:str=woot +#foo=(2015,2018) ]',
    '[ test:str=woot .seen=(2014,2015) ]',
    'graph:cluster=abcd | noderefs -d 2 --join',
    'test:pivcomp=(foo,bar) :lulz -+> test:str',
    'ps:person=$pers -> edge:has -> geo:place',
    'ps:person=$pers -> edge:has -> inet:ipv4',
    '[meta:seen=(abcd, (test:str, pennywise))]',
    'test:int +:loc^=us.va.fairfax.reston',
    'test:str [+#foo.bar=(2000,20020601)]',
    'test:str +test:str:tick<=201808021202',
    'test:str +test:str:tick>=201808021202',
    'test:str +:tick=(20150102, "-3 day")',
    'test:str +:tick=(20150201, "+1 day")',
    'test:str=woot $foo=#foo +.seen@=$foo',
    'geo:place:latlong*near=((0, 0), 50m)',
    'geo:place=$place <- edge:has <- inet:ipv4',
    'geo:place=$place <- edge:has <- ps:person',
    'inet:ipv4 +inet:ipv4=1.2.3.1-1.2.3.3',
    'inet:user | limit 10 | [ +#foo.bar ]',
    '[ inet:user=visi inet:user=whippit ]',
    'test:int:loc^=us.va.fairfax.chantilly',
    'test:str +:tick=(20150102, "+- 2day")',
    'test:str +:tick@=(20150102, "-4 day")',
    'iden 2cdd997872b10a65407ad5fadfa28e0d',
    'test:pivcomp | noderefs --join --degrees 2',
    'test:guid +test:guid*range=(abcd, dcbe)',
    '[test:int=5 :loc=us.va.fairfax.reston]',
    '[ test:str=visi test:int=20 +#foo.bar ]',
    'inet:user | limit 10 | +inet:user=visi',
    'ps:person=$pers -> edge:wentto -> inet:ipv4',
    '[test:int=7 :loc=us.va.fairfax.herndon]',
    'test:int +:loc^=us.va.fairfax.chantilly',
    'test:str=123 | noderefs --traverse-edge',
    '[ test:str=foo test:str=bar ] | sleep 10',
    '[ test:str=foo test:str=bar test:int=42 ]',
    '[inet:dns:query=(tcp://1.2.3.4, "", 1)]',
    '[ inet:ipv4 = 94.75.194.194 :loc = nl ]',
    '[edge:refs=((test:str, 123), (test:int, 123))]',
    'meta:source=8f1401de15918358d5247e21ca29a814',
    'test:comp +:haha*range=(grinch, meanone)',
    'test:str=123 [:baz="test:guid:tick=2015"]',
    'test:str +:tick@=("now+2days", "-3 day")',
    '[ geo:place="*" :latlong=(-30.0,20.22) ]',
    '[ inet:fqdn=woot.com +#bad=(2015,2016) ]',
    'test:str=1234 test:str=duck test:str=knight',
    'test:str=pennywise | noderefs --join -d 9',
    '[edge:has=((test:str, foobar), (test:str, foo))]',
    'inet:dns:a=(woot.com,1.2.3.4) $newp=.seen',
    '[ inet:dns:a=(woot.com, 1.2.3.4) +#yepr ]',
    '[ test:str=foo +#bar ] { [ +#baz ] -#bar }',
    'test:str +:tick@=(20150102+1day, "-4 day")',
    'test:str +:tick*range=(19701125, 20151212)',
    '[ inet:ipv4=1.2.3.0/30 inet:ipv4=5.5.5.5 ]',
    'test:str=bar test:pivcomp=(foo,bar) [+#test.bar]',
    '[ test:str=foo +#bar ] +(#baz or not .seen)',
    'test:str=pennywise | noderefs -d 3 -ot=omit',
    'for $fqdn in $fqdns { [ inet:fqdn=$fqdn ] }',
    'inet:dns:a -{ :ipv4 -> inet:ipv4 -:loc=us }',
    'inet:dns:a -{ :ipv4 -> inet:ipv4 +:loc=us }',
    'inet:dns:a +{ :ipv4 -> inet:ipv4 -:loc=us }',
    'inet:dns:a +{ :ipv4 -> inet:ipv4 +:loc=us }',
    '[ inet:dns:a = ( woot.com , 12.34.56.78 ) ]',
    '[ inet:fqdn=vertex.link inet:ipv4=1.2.3.4 ]',
    'inet:ipv4=1.2.3.4 +( { -> inet:dns:a }<=1 )',
    'inet:ipv4=1.2.3.4 +( { -> inet:dns:a }>=3 )',
    '[ test:comp=(10, haha) +#foo.bar -#foo.bar ]',
    'test:str=a +:tick*range=(20000101, 20101201)',
    '[ inet:dns:a=(vertex.link, 5.5.5.5) +#nope ]',
    '[ test:comp=(127,newp) ] [test:comp=(127,127)]',
    '[test:int=6 :loc=us.va.fairfax.restonheights]',
    '[test:str=a] switch $woot { hehe: {[+#baz]} }',
    'test:str=pennywise | noderefs -d 3 -of=meta:source',
    'geo:place:latlong*near=((34.1, -118.3), 10km)',
    'inet:dns:a +{ :ipv4 -> inet:ipv4 -:asn=1234 }',
    'inet:dns:a +{ :ipv4 -> inet:ipv4 +:asn=1234 }',
    'inet:fqdn=woot.com -> inet:dns:a -> inet:ipv4',
    'test:pivcomp=(foo,bar) -{ :lulz -> test:str +#baz }',
    'test:str=pennywise | noderefs -d 3 -otf=meta:source',
    '[ test:str=visi +#foo.bar ] -> # [ +#baz.faz ]',
    'geo:place -:latlong*near=((34.1, -118.3), 50m)',
    'inet:asn=10 | noderefs -of inet:ipv4 --join -d 3',
    'test:str +:bar*range=((test:str, c), (test:str, q))',
    '[ test:str=oof +#bar ] { [ test:int=0xdeadbeef ] }',
    'inet:ipv4=12.34.56.78 [ :loc = us.oh.wilmington ]',
    'test:str=pennywise | noderefs -d 3 --omit-tag=omit',
    '[ inet:dns:a=(woot.com,1.2.3.4) .seen=(2015,2016) ]',
    'inet:dns:a=(woot.com,1.2.3.4) [ .seen=(2015,2018) ]',
    '[inet:dns:query=(tcp://1.2.3.4, "foo*.haha.com", 1)]',
    '[ test:pivcomp=(hehe,haha) :tick=2015 +#foo=(2014,2016) ]',
    '[edge:refs=((test:int, 16), (test:comp, (9999, greenham)))]',
    'test:str=pennywise | noderefs -d 3 --omit-form=meta:source',
    '[ test:str=woot +#foo=(2015,2018) .seen=(2014,2016) ]',
    '[test:comp=(3, foob) +#meep.gorp +#bleep.zlorp +#cond]',
    'inet:dns:a=(woot.com,1.2.3.4) $hehe=:fqdn -:fqdn=$hehe',
    'inet:dns:a=(woot.com,1.2.3.4) $hehe=:fqdn +:fqdn=$hehe',
    'test:pivcomp=(foo,bar) +{ :lulz -> test:str +#baz } +test:pivcomp',
    'geo:place +geo:place:latlong*near=((34.1, -118.3), 10km)',
    'inet:dns:query=(tcp://1.2.3.4, "", 1) :name -> inet:fqdn',
    '[meta:source=abcd +#omit.nopiv] [meta:seen=(abcd, (test:pivtarg, foo))]',
    'test:str=pennywise | noderefs --join -d 9 --traverse-edge',
    'inet:dns:a=(woot.com,1.2.3.4) $hehe=:fqdn inet:fqdn=$hehe',
    '[inet:ipv4=1.2.3.4 :asn=10] [meta:seen=(abcd, (inet:asn, 10))]',
    '[test:str=c] switch $woot { hehe: {[+#baz]} *: {[+#jaz]} }',
    'geo:place:latlong*near=(("34.118560", "-118.300370"), 50m)',
    'ps:person=$pers -> edge:wentto +:time@=(2014,2017) -> geo:place',
    '[ test:str=woot +#foo=(2015,2018) +#bar .seen=(2014,2016) ]',
    'test:str=pennywise | noderefs -d 3 -ott=omit.nopiv -ott=test',
    'for ($fqdn, $ipv4) in $dnsa { [ inet:dns:a=($fqdn,$ipv4) ] }',
    'geo:place:latlong*near=(("34.118560", "-118.300370"), 2600m)',
    'test:comp +test:comp*range=((1024, grinch), (4096, zemeanone))',
    '[ inet:ipv4=1.2.3.4 :loc=us inet:dns:a=(vertex.link,1.2.3.4) ]',
    '[ inet:ipv4=4.3.2.1 :loc=zz inet:dns:a=(example.com,4.3.2.1) ]',
    'test:str=pennywise | noderefs -d 3 --omit-traversal-form=meta:source',
    'test:pivcomp=(hehe,haha) $ticktock=#foo -> test:pivtarg +.seen@=$ticktock',
    "[test:comp=(123, test) test:comp=(123, duck) test:comp=(123, mode)]"
    'for ($fqdn,$ipv4,$boom) in $dnsa { [ inet:dns:a=($fqdn,$ipv4) ] }',
    'inet:fqdn +#bad $fqdnbad=#bad -> inet:dns:a:fqdn +.seen@=$fqdnbad',
    'media:news = 00a1f0d928e25729b9e86e2d08c127ce [ :summary = \"\" ]',
    '[edge:refs=((test:comp, (2048, horton)), (test:comp, (4096, whoville)))]',
    'test:str +:.seen*range=((20090601, 20090701), (20110905, 20110906,))',
    '[ inet:dns:a=(woot.com, 1.2.3.4) inet:dns:a=(vertex.link, 1.2.3.4) ]',
    'edge:refs +:n1*range=((test:comp, (1000, green)), (test:comp, (3000, ham)))',
    'inet:dns:query=(tcp://1.2.3.4, "foo*.haha.com", 1) :name -> inet:fqdn',
    'inet:dns:a = (woot.com,  12.34.56.78) [ .seen=( 201708010123, \"?\" ) ]',
    'test:int | noderefs | +test:comp*range=((1000, grinch), (4000, whoville))',
    '[edge:refs=((test:comp, (9001, "A mean one")), (test:comp, (40000, greeneggs)))]',
    'inet:dns:a=(woot.com,1.2.3.4) $seen=.seen :fqdn -> inet:fqdn [ .seen=$seen ]',
    '[ inet:fqdn=woot.com inet:fqdn=vertex.link ] [ inet:user = :zone ] +inet:user',
    'inet:dns:a = (woot.com,  12.34.56.78) [ .seen=( 201708010123, 201708100456 ) ]',
    '[test:str=c] switch $woot { hehe: {[+#baz]} haha hoho: {[+#faz]} "lolz:lulz": {[+#jaz]} }',
    '[ inet:fqdn = hehe.com inet:ipv4 = 127.0.0.1 hash:md5 = d41d8cd98f00b204e9800998ecf8427e]',
    'test:str=pennywise | noderefs -d 3 --omit-traversal-tag=omit.nopiv --omit-traversal-tag=test',
    'geo:place=abcd $latlong=:latlong $radius=:radius | spin | tel:mob:telem:latlong*near=($latlong, 3km)',
    'inet:ipv4=12.34.56.78 inet:fqdn=woot.com [ inet:ipv4=1.2.3.4 :asn=10101 inet:fqdn=woowoo.com +#my.tag ]',
    'test:str +#*',
    'test:str -#*',
    'test:str +#foo.*.baz',
    'test:str +#*.bad',
    'test:str +#foo.**.baz',
    'test:str +#**.bar.baz',
    'test:str +#**.baz',
    '''
        for $foo in $foos {

            ($fqdn, $ipv4) = $foo.split("|")

            [ inet:dns:a=($fqdn, $ipv4) ]
        } ''',
    ''' /* A comment */ test:int ''',
    ''' test:int // a comment''',
    '''/* multi
         line */ test:int ''',
    '''
        /* A
            multiline
            comment */
        [ inet:ipv4=1.2.3.4 ] // this is a comment
        // and this too...

        switch $foo {

            // The bar case...

            bar: {
                [ +#hehe.haha ]
            }

            /*
                The
                baz
                case
            */
            baz faz: {}
        } ''',
    '''
        inet:fqdn | graph
                    --degrees 2
                    --filter { -#nope }
                    --pivot { <- meta:seen <- meta:source }
                    --form-pivot inet:fqdn {<- * | limit 20}
                    --form-pivot inet:fqdn {-> * | limit 20}
                    --form-filter inet:fqdn {-inet:fqdn:issuffix=1}
                    --form-pivot syn:tag {-> *}
                    --form-pivot * {-> #} ''',
    '''
        for $foo in $foos {

            [ inet:ipv4=1.2.3.4 ]

            switch $foo {
                bar: { [ +#ohai ] break }
                baz: { [ +#visi ] continue }
            }

            [ inet:ipv4=5.6.7.8 ]
            [ +#hehe ]
        } ''',
    'test:int=1234 [test:str=$node.value()] -test:int',
    'test:int=1234 [test:str=$node.form()] -test:int',
    '''
        for $foo in $foos {

            ($fqdn, $ipv4) = $foo.split("|")

            [ inet:dns:a=($fqdn, $ipv4) ]
        } ''',
    ' [ test:int=$hehe.haha ] ',
    '($tick, $tock) = .seen',
    '''
    for $tag in $node.tags() {
        -> test:int [ +#$tag ]
    } ''',
    '''
    for $tag in $node.tags(fo*) {
        -> test:int [ -#$tag ]
    }
    ''',
]

# Generated with gen_parse_list below
_ParseResults = [
    'Query: []',
    'Query: [LiftTag: [TagName: foo]]',
    'Query: [CmdOper: [Const: help, Const: ()]]',
    'Query: [LiftProp: [Const: edge:refs]]',
    'Query: [LiftTag: [VarValue: [Const: tag]]]',
    'Query: [LiftProp: [Const: edge:wentto]]',
    'Query: [EditTagDel: [TagName: foo]]',
    'Query: [LiftProp: [Const: syn:tag]]',
    'Query: [LiftProp: [Const: test:str]]',
    'Query: [LiftProp: [Const: .created]]',
    'Query: [LiftTagTag: [TagName: baz.faz]]',
    'Query: [LiftProp: [Const: inet:fqdn]]',
    'Query: [LiftProp: [Const: inet:user]]',
    'Query: [LiftTag: [TagName: test.baz]]',
    'Query: [LiftTag: [TagName: hehe.haha]]',
    'Query: [LiftProp: [Const: inet:dns:a]]',
    'Query: [LiftPropBy: [Const: test:int, Const: <, Const: 20]]',
    'Query: [LiftPropBy: [Const: test:int, Const: >, Const: 20]]',
    'Query: [LiftPropBy: [Const: test:int, Const: <, Const: 30]]',
    'Query: [LiftPropBy: [Const: test:int, Const: >, Const: 30]]',
    'Query: [LiftPropBy: [Const: test:int, Const: <=, Const: 20]]',
    'Query: [LiftPropBy: [Const: test:int, Const: >=, Const: 20]]',
    'Query: [LiftPropBy: [Const: test:int, Const: <=, Const: 30]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foo]]',
    'Query: [LiftFormTag: [Const: test:str, TagName: foo]]',
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, VarValue: [Const: foo]]]',
    'Query: [LiftPropBy: [Const: test:int, Const: =, Const: 1234]]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 20]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, VarValue: [Const: foo]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: ohmy]]',
    'Query: [LiftPropBy: [Const: .created, Const: <, Const: 2010]]',
    'Query: [LiftPropBy: [Const: .created, Const: >, Const: 2010]]',
    "Query: [CmdOper: [Const: iden, Const: ('deadb33f',)]]",
    'Query: [LiftProp: [Const: test:comp], PivotOut: [], isjoin=False]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: =, Const: u]]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 42]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: =, Const: ]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: u]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: =, Const: us]]',
    'Query: [LiftPropBy: [Const: test:str, Const: ~=, Const: zip]]',
    'Query: [LiftPropBy: [Const: .created, Const: =, Const: 2001]]',
    'Query: [LiftPropBy: [Const: .seen, Const: ~=, Const: ^r]]',
    'Query: [LiftPropBy: [Const: test:int, Const: =, Const: 8675309]]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 99999]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: ]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: 23]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: u]]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: us]]',
    'Query: [LiftProp: [Const: test:str], EditTagDel: [TagName: foo]]',
    'Query: [LiftFormTag: [Const: test:str, TagName: foo.bar]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: hello]]',
    'Query: [LiftProp: [Const: .seen], EditUnivDel: [UnivProp: .seen]]',
    'Query: [LiftPropBy: [Const: inet:ipv4:loc, Const: =, Const: us]]',
    'Query: [LiftPropBy: [Const: inet:ipv4:loc, Const: =, Const: zz]]',
    'Query: [LiftTag: [VarValue: [Const: tag]], EditTagDel: [VarValue: [Const: tag]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: ]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: u]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us]]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: us.]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: =, Const: us.v]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: bar], PivotIn: [], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: hehe]]',
    'Query: [LiftProp: [Const: test:str], EditPropDel: [RelProp: tick]]',
    'Query: [LiftPropBy: [Const: file:bytes:size, Const: =, Const: 4]]',
    "Query: [CmdOper: [Const: movetag, Const: ('#a.b', '#a.m')]]",
    'Query: [LiftPropBy: [Const: test:pivcomp:tick, Const: =, VarValue: [Const: foo]]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: a.b], FiltOper: [Const: +, TagCond: [TagMatch: foo]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: ]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: 23]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us]]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: us.v]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: =, Const: us.va]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: bar], PivotIn: [], isjoin=True]',
    'Query: [LiftFormTag: [Const: test:str, TagName: foo, Const: @=, Const: 2016]]',
    'Query: [LiftPropBy: [Const: test:str:tick, Const: =, Const: 2015]]',
    'Query: [LiftPropBy: [Const: inet:fqdn, Const: =, Const: woot.com]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, VarValue: [Const: foo]]]',
    'Query: [LiftProp: [Const: test:pivcomp], CmdOper: [Const: noderefs, Const: ()]]',
    'Query: [LiftProp: [Const: test:pivcomp], FormPivot: [AbsProp: test:int], isjoin=False]',
    'Query: [LiftPropBy: [Const: test:int, Const: =, Const: 3735928559]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us.v]]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: us.va]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foo], PivotInFrom: [AbsProp: edge:has], isjoin=False]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: visi], PivotToTags: [TagMatch: *], isjoin=False]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('1',)]]",
    "Query: [CmdOper: [Const: movetag, Const: ('#hehe', '#woot')]]",
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: hehe, Const: haha]]]',
    'Query: [LiftProp: [Const: test:comp], FormPivot: [AbsProp: test:int], isjoin=False]',
    "Query: [LiftProp: [Const: test:guid], CmdOper: [Const: max, Const: ('tick',)]]",
    "Query: [LiftProp: [Const: test:guid], CmdOper: [Const: min, Const: ('tick',)]]",
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 3], EditPropSet: [RelProp: loc, Const: ]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.v]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us.va]]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: us.va.]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:int, Const: >, Const: 10]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:int, Const: <, Const: 30]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, TagValuCond: [TagMatch: foo, Const: @=, Const: 2016]]]',
    'Query: [LiftProp: [Const: test:str], EditTagAdd: [TagName: foo.bar]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foo], PivotInFrom: [AbsProp: edge:has], isjoin=True]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, Const: 2015]]]',
    'Query: [LiftPropBy: [Const: .created, Const: =, Const: {created}]]',
    'Query: [LiftProp: [Const: inet:ipv4], FormPivot: [AbsProp: test:str], isjoin=False]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('1',)]]",
    'Query: [EditNodeAdd: [AbsProp: test:pivcomp, List: [Const: foo, Const: 123]]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: foo.bar], PivotOut: [], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 12], EditPropSet: [RelProp: loc, Const: us]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va]]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: =, Const: us.va.sy]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:int, Const: >=, Const: 10]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:int, Const: <=, Const: 30]]]',
    'Query: [LiftProp: [Const: inet:dns:a], PropPivotOut: [RelProp: ipv4], isjoin=False]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 10.2.1.1/28]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4]]',
    'Query: [EditNodeAdd: [AbsProp: test:pivcomp, List: [Const: foo, Const: bar]]]',
    "Query: [CmdOper: [Const: reindex, Const: ('--form-counts',)]]",
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: -, TagCond: [TagMatch: test]], PivotIn: [], isjoin=False]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: -, TagCond: [TagMatch: test]], PivotOut: [], isjoin=False]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: bar], EditTagAdd: [TagName: baz]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: foo], EditTagAdd: [TagName: bar]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foo], CmdOper: [Const: delnode, Const: ()]]',
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: foo, Const: bar]], PivotOut: [], isjoin=False]',
    'Query: [LiftPropBy: [Const: meta:seen:meta:source, Const: =, VarValue: [Const: sorc]], PivotOut: [], isjoin=False]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: test:str, Const: foo]]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: -, TagCond: [TagMatch: test]], PivotIn: [], isjoin=True]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: -, TagCond: [TagMatch: test]], PivotOut: [], isjoin=True]',
    'Query: [LiftPropBy: [Const: test:comp:haha, Const: ~=, Const: ^lulz]]',
    'Query: [LiftPropBy: [Const: test:comp:haha, Const: ~=, Const: ^zerg]]',
    'Query: [LiftPropBy: [Const: test:int, Const: =, Const: 123], CmdOper: [Const: noderefs, Const: ()]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us.va.sy]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: 123], CmdOper: [Const: noderefs, Const: ()]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foobar], FormPivot: [AbsProp: edge:has], isjoin=True]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: foo], EditTagAdd: [VarValue: [Const: tag]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: haha], EditTagAdd: [TagName: foo]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: [Const: 2015]]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: visi], PivotToTags: [TagMatch: baz.*], isjoin=False]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: visi], PivotToTags: [TagMatch: foo.*], isjoin=False]',
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: foo, Const: bar]], PivotOut: [], isjoin=True]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: test:guid, Const: *]]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: test:pivcomp]], PivotOut: [], isjoin=False]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: test:str]], PivotIn: [], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:comp, List: [Const: 1234, Const: 5678]]]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 10], EditPropSet: [RelProp: loc, Const: us.va]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: us.va.fair]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: =, Const: us.va.syria]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foo], FiltOper: [Const: +, TagValuCond: [TagMatch: lol, Const: @=, Const: 2014]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foo], FiltOper: [Const: +, TagValuCond: [TagMatch: lol, Const: @=, Const: 2016]]]',
    "Query: [LiftProp: [Const: test:str], CmdOper: [Const: noderefs, Const: ('-d', '3')]]",
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: woot.com]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 192.168.1.0/24]]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('--woot',)]]",
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: test:pivcomp]], PivotOut: [], isjoin=True]',
    'Query: [LiftTag: [TagName: test.bar], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: test:str]], PivotIn: [], isjoin=True]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: =, Const: us.va.sydney]]',
    'Query: [LiftFormTag: [Const: test:str, TagName: foo, Const: @=, List: [Const: 2012, Const: 2022]]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 1.2.3.1-1.2.3.3]]',
    "Query: [LiftProp: [Const: test:pivcomp], CmdOper: [Const: noderefs, Const: ('--join',)]]",
    'Query: [EditNodeAdd: [AbsProp: test:guid, Const: *], EditPropSet: [RelProp: tick, Const: 2001]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.fair]]]',
    "Query: [LiftProp: [Const: test:str], CmdOper: [Const: delnode, Const: ('--force',)]]",
    'Query: [LiftPropBy: [Const: test:str:tick, Const: <, Const: 201808021202]]',
    'Query: [LiftPropBy: [Const: test:str:tick, Const: >, Const: 201808021202]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: woot], EditPropSet: [UnivProp: .seen, Const: 20]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, Const: 2012]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, Const: 2015]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, TagPropValue: [TagName: bar]]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, TagPropValue: [TagName: baz]]]]',
    "Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 1.2.3.4], CmdOper: [Const: limit, Const: ('20',)]]",
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: asn::name], Const: =, Const: visi]]]',
    "Query: [LiftProp: [Const: inet:ipv4], CmdOper: [Const: reindex, Const: ('--subs',)]]",
    'Query: [CmdOper: [Const: sudo, Const: ()], LiftPropBy: [Const: test:int, Const: =, Const: 6], CmdOper: [Const: delnode, Const: ()]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: aaa.barbarella.ddd]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: foo.bar], FormPivot: [AbsProp: test:str], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:guid, Const: abcd], EditPropSet: [RelProp: tick, Const: 2015]]',
    "Query: [LiftPropBy: [Const: test:int, Const: =, Const: 123], CmdOper: [Const: noderefs, Const: ('-te',)]]",
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 9], EditPropSet: [RelProp: loc, Const: us.ओं]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: us.va.fairfax]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us.va.sydney]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foo bar], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: test:str]]]',
    "Query: [LiftProp: [Const: test:str], CmdOper: [Const: noderefs, Const: ('-d', '3', '-u')]]",
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: [Const: -1 day]]]]',
    'Query: [LiftPropBy: [Const: test:str:tick, Const: <=, Const: 201808021202]]',
    'Query: [LiftPropBy: [Const: test:str:tick, Const: >=, Const: 201808021202]]',
    'Query: [LiftPropBy: [Const: .created, Const: *range=, List: [Const: 2010, Const: 3001]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:asn, Const: 200], EditPropSet: [RelProp: name, Const: visi]]',
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: woot.com], PivotOut: [], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.1-1.2.3.3]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 192.168.1.0/24]]',
    'Query: [LiftPropBy: [Const: test:pivtarg, Const: =, Const: hehe], EditPropSet: [UnivProp: .seen, Const: 2015]]',
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: edge:has], isjoin=False, PivotOut: [], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:guid, Const: *], EditPropSet: [RelProp: tick, Const: 2015]]',
    'Query: [EditNodeAdd: [AbsProp: test:guid, Const: *], EditPropSet: [RelProp: tick, Const: 2016]]',
    'Query: [EditNodeAdd: [AbsProp: test:guid, Const: *], EditPropSet: [RelProp: tick, Const: 2017]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: us.va.fairfax.]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: bar], FormPivot: [AbsProp: test:pivcomp:lulz], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: beep], EditNodeAdd: [AbsProp: test:str, Const: boop]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, TagValuCond: [TagMatch: foo, Const: @=, List: [Const: 2014, Const: 2019]]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, TagValuCond: [TagMatch: foo, Const: @=, List: [Const: 2015, Const: 2018]]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: foo], EditNodeAdd: [AbsProp: test:str, Const: bar]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: haha], EditTagAdd: [TagName: bar, Const: 2015]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: haha], EditTagAdd: [TagName: bar, Const: 2016]]',
    'Query: [LiftPropBy: [Const: .created, Const: *range=, List: [Const: 2010, Const: ?]]]',
    'Query: [LiftPropBy: [Const: geo:place, Const: =, VarValue: [Const: place]], PivotInFrom: [AbsProp: edge:has], isjoin=False, PivotIn: [], isjoin=False]',
    'Query: [LiftPropBy: [Const: inet:fqdn, Const: =, Const: woot.com], CmdOper: [Const: delnode, Const: ()]]',
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: foo, Const: bar]], FormPivot: [AbsProp: test:pivtarg], isjoin=False]',
    'Query: [LiftPropBy: [Const: meta:seen:meta:source, Const: =, VarValue: [Const: sorc]], PropPivotOut: [RelProp: node], isjoin=False]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4]]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: test:str, Const: foo], EditTagAdd: [TagName: lol]]',
    'Query: [LiftProp: [Const: test:comp], PivotOut: [], isjoin=False, CmdOper: [Const: uniq, Const: ()], CmdOper: [Const: count, Const: ()]]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 1], EditPropSet: [RelProp: loc, Const: us.va.syria]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.fairfax]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us.va. syria]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: bar], FormPivot: [AbsProp: test:pivcomp:lulz], isjoin=True]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foo bar], EditPropDel: [RelProp: tick]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: hello], EditPropSet: [RelProp: tick, Const: 2001]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: hello], EditPropSet: [RelProp: tick, Const: 2002]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], EditPropSet: [RelProp: asn, Const: 20]]',
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: foo, Const: bar]], FormPivot: [AbsProp: test:pivtarg], isjoin=True]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: baz.faz], EditTagAdd: [TagName: foo.bar]]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 2], EditPropSet: [RelProp: loc, Const: us.va.sydney]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.fairfax.]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], EditPropSet: [RelProp: asn, Const: 200]]',
    "Query: [CmdOper: [Const: movetag, Const: ('#aaa.b', '#aaa.barbarella')]]",
    "Query: [LiftProp: [Const: test:pivcomp], CmdOper: [Const: noderefs, Const: ('--join', '-d', '3')]]",
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: edge:wentto], isjoin=False, PivotOut: [], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 4], EditPropSet: [RelProp: loc, Const: us.va.fairfax]]',
    'Query: [VarSetOper: [Const: bar, Const: 5.5.5.5], EditNodeAdd: [AbsProp: inet:ipv4, VarValue: [Const: bar]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, FuncCall: [VarDeref: [VarValue: [Const: blob], Const: split], CallArgs: [Const: |], CallKwargs: []]]]',
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: -, AbsPropCond: [AbsProp: inet:ipv4, Const: =, Const: 1.2.3.0/30]]]',
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: +, AbsPropCond: [AbsProp: inet:ipv4, Const: =, Const: 1.2.3.0/30]]]',
    'Query: [EditNodeAdd: [AbsProp: test:pivcomp, List: [Const: xxx, Const: yyy]], EditPropSet: [RelProp: width, Const: 42]]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: test:str, Const: 123], EditPropSet: [RelProp: tick, Const: 2018]]',
    'Query: [LiftPropBy: [Const: syn:tag, Const: =, Const: foo.bar], FormPivot: [AbsProp: test:str:tick], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 1], EditNodeAdd: [AbsProp: test:int, Const: 2], EditNodeAdd: [AbsProp: test:int, Const: 3]]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 8], EditPropSet: [RelProp: loc, Const: us.ca.sandiego]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, TagValuCond: [TagMatch: foo, Const: @=, List: [Const: 2014, Const: 20141231]]]]',
    'Query: [LiftProp: [Const: test:str], EditTagAdd: [TagName: foo.bar, List: [Const: 2000, Const: 2002]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foo bar], FiltOper: [Const: -, HasAbsPropCond: [AbsProp: test:str:tick]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: foo bar], EditPropSet: [RelProp: tick, Const: 2018]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, List: [Const: 2015, Const: +1 day]]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: [Const: now, Const: -1 day]]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: visi], EditTagAdd: [TagName: foo.bar], PivotToTags: [TagMatch: ], isjoin=False]',
    'Query: [LiftPropBy: [Const: inet:fqdn, Const: =, Const: woot.com], FormPivot: [AbsProp: inet:dns:a], isjoin=False]',
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: +, AbsPropCond: [AbsProp: inet:ipv4, Const: =, Const: 10.2.1.4/31]]]',
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: +, AbsPropCond: [AbsProp: inet:ipv4, Const: =, Const: 10.2.1.4/32]]]',
    'Query: [EditNodeAdd: [AbsProp: test:pivcomp, List: [Const: foo, Const: bar]], EditPropSet: [RelProp: tick, Const: 2018]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: foobar], FormPivot: [AbsProp: edge:has], isjoin=False, PivotInFrom: [AbsProp: test:str], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: foo], EditPropSet: [RelProp: tick, Const: 201808021201]]',
    "Query: [LiftProp: [Const: test:str], CmdOper: [Const: noderefs, Const: ('-d', '3', '--unique')]]",
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: [Const: 2015, Const: +1 day]]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, List: [Const: 2012, Const: 2013]]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: woot], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, List: [Const: 2012, Const: 2015]]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: [Const: woot.com, Const: 1.2.3.4]]]',
    "Query: [LiftProp: [Const: test:pivcomp], CmdOper: [Const: noderefs, Const: ('-j', '--degrees', '2')]]",
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: test:cycle0, Const: foo], EditPropSet: [RelProp: test:cycle1, Const: bar]]',
    'Query: [CmdOper: [Const: sudo, Const: ()], EditNodeAdd: [AbsProp: test:cycle1, Const: bar], EditPropSet: [RelProp: test:cycle0, Const: foo]]',
    'Query: [LiftProp: [Const: test:comp], FiltOper: [Const: +, OrCond: [RelPropCond: [RelPropValue: [RelProp: hehe], Const: <, Const: 2], RelPropCond: [RelPropValue: [RelProp: haha], Const: =, Const: foob]]]]',
    'Query: [LiftProp: [Const: test:comp], FiltOper: [Const: +, OrCond: [RelPropCond: [RelPropValue: [RelProp: hehe], Const: <, Const: 2], RelPropCond: [RelPropValue: [RelProp: haha], Const: =, Const: test]]]]',
    'Query: [LiftProp: [Const: test:comp], FiltOper: [Const: +, OrCond: [RelPropCond: [RelPropValue: [RelProp: hehe], Const: <, Const: 2], TagCond: [TagMatch: meep.gorp]]]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: us.va.fairfax.reston]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: abcd], EditPropSet: [RelProp: tick, Const: 2015], EditTagAdd: [TagName: cool], LiftPropBy: [Const: test:str, Const: =, Const: foobar], FormPivot: [AbsProp: edge:has], isjoin=False, PivotInFrom: [AbsProp: test:str], isjoin=True]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3')]]",
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: [Const: now-1day, Const: ?]]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, List: [VarValue: [Const: test], Const: +- 2day]]]]',
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: foo, Const: bar]], PropPivot: [RelPropValue: [RelProp: lulz], AbsProp: test:str], isjoin=False]',
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: foo, Const: bar]], PropPivot: [RelPropValue: [RelProp: targ], AbsProp: test:pivtarg], isjoin=False]',
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: edge:wentto], isjoin=False, PropPivotOut: [RelProp: n2], isjoin=False]',
    'Query: [LiftProp: [Const: test:comp], FiltOper: [Const: +, AndCond: [RelPropCond: [RelPropValue: [RelProp: hehe], Const: <, Const: 2], RelPropCond: [RelPropValue: [RelProp: haha], Const: =, Const: foob]]]]',
    'Query: [LiftProp: [Const: test:comp], FiltOper: [Const: +, AndCond: [RelPropCond: [RelPropValue: [RelProp: hehe], Const: <, Const: 2], RelPropCond: [RelPropValue: [RelProp: haha], Const: =, Const: test]]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: foo], EditTagAdd: [TagName: bar], FiltOper: [Const: +, NotCond: [HasRelPropCond: [UnivProp: .seen]]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: foo], EditNodeAdd: [AbsProp: test:str, Const: bar], CmdOper: [Const: spin, Const: ()]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: hehe], EditTagAdd: [TagName: foo, List: [Const: 2014, Const: 2016]]]',
    "Query: [EditNodeAdd: [AbsProp: test:str, Const: hehe], CmdOper: [Const: iden, Const: ('abcd',)], CmdOper: [Const: count, Const: ()]]",
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:str:tick, Const: <, Const: 201808021202]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:str:tick, Const: >, Const: 201808021202]]]',
    'Query: [LiftPropBy: [Const: test:str:tick, Const: =, List: [Const: 20131231, Const: +2 days]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: woot], EditTagAdd: [TagName: foo, List: [Const: 2015, Const: 2018]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: woot], EditPropSet: [UnivProp: .seen, List: [Const: 2014, Const: 2015]]]',
    "Query: [LiftPropBy: [Const: graph:cluster, Const: =, Const: abcd], CmdOper: [Const: noderefs, Const: ('-d', '2', '--join')]]",
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: foo, Const: bar]], PropPivot: [RelPropValue: [RelProp: lulz], AbsProp: test:str], isjoin=True]',
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: edge:has], isjoin=False, FormPivot: [AbsProp: geo:place], isjoin=False]',
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: edge:has], isjoin=False, FormPivot: [AbsProp: inet:ipv4], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: meta:seen, List: [Const: abcd, List: [Const: test:str, Const: pennywise]]]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.fairfax.reston]]]',
    'Query: [LiftProp: [Const: test:str], EditTagAdd: [TagName: foo.bar, List: [Const: 2000, Const: 20020601]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:str:tick, Const: <=, Const: 201808021202]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:str:tick, Const: >=, Const: 201808021202]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, List: [Const: 20150102, Const: -3 day]]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, List: [Const: 20150201, Const: +1 day]]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: woot], VarSetOper: [Const: foo, TagPropValue: [TagName: foo]], FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, VarValue: [Const: foo]]]]',
    'Query: [LiftPropBy: [Const: geo:place:latlong, Const: *near=, List: [List: [Const: 0, Const: 0], Const: 50m]]]',
    'Query: [LiftPropBy: [Const: geo:place, Const: =, VarValue: [Const: place]], PivotInFrom: [AbsProp: edge:has], isjoin=False, PivotInFrom: [AbsProp: inet:ipv4], isjoin=False]',
    'Query: [LiftPropBy: [Const: geo:place, Const: =, VarValue: [Const: place]], PivotInFrom: [AbsProp: edge:has], isjoin=False, PivotInFrom: [AbsProp: ps:person], isjoin=False]',
    'Query: [LiftProp: [Const: inet:ipv4], FiltOper: [Const: +, AbsPropCond: [AbsProp: inet:ipv4, Const: =, Const: 1.2.3.1-1.2.3.3]]]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('10',)], EditTagAdd: [TagName: foo.bar]]",
    'Query: [EditNodeAdd: [AbsProp: inet:user, Const: visi], EditNodeAdd: [AbsProp: inet:user, Const: whippit]]',
    'Query: [LiftPropBy: [Const: test:int:loc, Const: ^=, Const: us.va.fairfax.chantilly]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: =, List: [Const: 20150102, Const: +- 2day]]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: [Const: 20150102, Const: -4 day]]]]',
    "Query: [CmdOper: [Const: iden, Const: ('2cdd997872b10a65407ad5fadfa28e0d',)]]",
    "Query: [LiftProp: [Const: test:pivcomp], CmdOper: [Const: noderefs, Const: ('--join', '--degrees', '2')]]",
    'Query: [LiftProp: [Const: test:guid], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:guid, Const: *range=, List: [Const: abcd, Const: dcbe]]]]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 5], EditPropSet: [RelProp: loc, Const: us.va.fairfax.reston]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: visi], EditNodeAdd: [AbsProp: test:int, Const: 20], EditTagAdd: [TagName: foo.bar]]',
    "Query: [LiftProp: [Const: inet:user], CmdOper: [Const: limit, Const: ('10',)], FiltOper: [Const: +, AbsPropCond: [AbsProp: inet:user, Const: =, Const: visi]]]",
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: edge:wentto], isjoin=False, FormPivot: [AbsProp: inet:ipv4], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 7], EditPropSet: [RelProp: loc, Const: us.va.fairfax.herndon]]',
    'Query: [LiftProp: [Const: test:int], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: ^=, Const: us.va.fairfax.chantilly]]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: 123], CmdOper: [Const: noderefs, Const: ('--traverse-edge',)]]",
    "Query: [EditNodeAdd: [AbsProp: test:str, Const: foo], EditNodeAdd: [AbsProp: test:str, Const: bar], CmdOper: [Const: sleep, Const: ('10',)]]",
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: foo], EditNodeAdd: [AbsProp: test:str, Const: bar], EditNodeAdd: [AbsProp: test:int, Const: 42]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:query, List: [Const: tcp://1.2.3.4, Const: , Const: 1]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 94.75.194.194], EditPropSet: [RelProp: loc, Const: nl]]',
    'Query: [EditNodeAdd: [AbsProp: edge:refs, List: [List: [Const: test:str, Const: 123], List: [Const: test:int, Const: 123]]]]',
    'Query: [LiftPropBy: [Const: meta:source, Const: =, Const: 8f1401de15918358d5247e21ca29a814]]',
    'Query: [LiftProp: [Const: test:comp], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: haha], Const: *range=, List: [Const: grinch, Const: meanone]]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: 123], EditPropSet: [RelProp: baz, Const: test:guid:tick=2015]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: [Const: now+2days, Const: -3 day]]]]',
    'Query: [EditNodeAdd: [AbsProp: geo:place, Const: *], EditPropSet: [RelProp: latlong, List: [Const: -30.0, Const: 20.22]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: woot.com], EditTagAdd: [TagName: bad, List: [Const: 2015, Const: 2016]]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: 1234], LiftPropBy: [Const: test:str, Const: =, Const: duck], LiftPropBy: [Const: test:str, Const: =, Const: knight]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('--join', '-d', '9')]]",
    'Query: [EditNodeAdd: [AbsProp: edge:has, List: [List: [Const: test:str, Const: foobar], List: [Const: test:str, Const: foo]]]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: [Const: woot.com, Const: 1.2.3.4]], VarSetOper: [Const: newp, UnivPropValue: [UnivProp: .seen]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: [Const: woot.com, Const: 1.2.3.4]], EditTagAdd: [TagName: yepr]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: foo], EditTagAdd: [TagName: bar], SubQuery: [Query: [EditTagAdd: [TagName: baz], FiltOper: [Const: -, TagCond: [TagMatch: bar]]]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: @=, List: [Const: 20150102+1day, Const: -4 day]]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: *range=, List: [Const: 19701125, Const: 20151212]]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.0/30], EditNodeAdd: [AbsProp: inet:ipv4, Const: 5.5.5.5]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: bar], LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: foo, Const: bar]], EditTagAdd: [TagName: test.bar]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: foo], EditTagAdd: [TagName: bar], FiltOper: [Const: +, OrCond: [TagCond: [TagMatch: baz], NotCond: [HasRelPropCond: [UnivProp: .seen]]]]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '-ot=omit')]]",
    'Query: [ForLoop: [Const: fqdn, VarValue: [Const: fqdns], SubQuery: [Query: [EditNodeAdd: [AbsProp: inet:fqdn, VarValue: [Const: fqdn]]]]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: -, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], isjoin=False, FiltOper: [Const: -, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us]]]]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: -, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], isjoin=False, FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us]]]]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: +, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], isjoin=False, FiltOper: [Const: -, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us]]]]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: +, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], isjoin=False, FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: loc], Const: =, Const: us]]]]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: [Const: woot.com, Const: 12.34.56.78]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: vertex.link], EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 1.2.3.4], FiltOper: [Const: +, SubqCond: [Query: [FormPivot: [AbsProp: inet:dns:a], isjoin=False], Const: <=, Const: 1]]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 1.2.3.4], FiltOper: [Const: +, SubqCond: [Query: [FormPivot: [AbsProp: inet:dns:a], isjoin=False], Const: >=, Const: 3]]]',
    'Query: [EditNodeAdd: [AbsProp: test:comp, List: [Const: 10, Const: haha]], EditTagAdd: [TagName: foo.bar], EditTagDel: [TagName: foo.bar]]',
    'Query: [LiftPropBy: [Const: test:str, Const: =, Const: a], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: tick], Const: *range=, List: [Const: 20000101, Const: 20101201]]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: [Const: vertex.link, Const: 5.5.5.5]], EditTagAdd: [TagName: nope]]',
    'Query: [EditNodeAdd: [AbsProp: test:comp, List: [Const: 127, Const: newp]], EditNodeAdd: [AbsProp: test:comp, List: [Const: 127, Const: 127]]]',
    'Query: [EditNodeAdd: [AbsProp: test:int, Const: 6], EditPropSet: [RelProp: loc, Const: us.va.fairfax.restonheights]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: a], SwitchCase: [VarValue: [Const: woot], CaseEntry: [Const: hehe, SubQuery: [Query: [EditTagAdd: [TagName: baz]]]]]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '-of=meta:source')]]",
    'Query: [LiftPropBy: [Const: geo:place:latlong, Const: *near=, List: [List: [Const: 34.1, Const: -118.3], Const: 10km]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: +, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], isjoin=False, FiltOper: [Const: -, RelPropCond: [RelPropValue: [RelProp: asn], Const: =, Const: 1234]]]]]]',
    'Query: [LiftProp: [Const: inet:dns:a], FiltOper: [Const: +, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: ipv4], AbsProp: inet:ipv4], isjoin=False, FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: asn], Const: =, Const: 1234]]]]]]',
    'Query: [LiftPropBy: [Const: inet:fqdn, Const: =, Const: woot.com], FormPivot: [AbsProp: inet:dns:a], isjoin=False, FormPivot: [AbsProp: inet:ipv4], isjoin=False]',
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: foo, Const: bar]], FiltOper: [Const: -, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: lulz], AbsProp: test:str], isjoin=False, FiltOper: [Const: +, TagCond: [TagMatch: baz]]]]]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '-otf=meta:source')]]",
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: visi], EditTagAdd: [TagName: foo.bar], PivotToTags: [TagMatch: ], isjoin=False, EditTagAdd: [TagName: baz.faz]]',
    'Query: [LiftProp: [Const: geo:place], FiltOper: [Const: -, RelPropCond: [RelPropValue: [RelProp: latlong], Const: *near=, List: [List: [Const: 34.1, Const: -118.3], Const: 50m]]]]',
    "Query: [LiftPropBy: [Const: inet:asn, Const: =, Const: 10], CmdOper: [Const: noderefs, Const: ('-of', 'inet:ipv4', '--join', '-d', '3')]]",
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: bar], Const: *range=, List: [List: [Const: test:str, Const: c], List: [Const: test:str, Const: q]]]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: oof], EditTagAdd: [TagName: bar], SubQuery: [Query: [EditNodeAdd: [AbsProp: test:int, Const: 0xdeadbeef]]]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 12.34.56.78], EditPropSet: [RelProp: loc, Const: us.oh.wilmington]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '--omit-tag=omit')]]",
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: [Const: woot.com, Const: 1.2.3.4]], EditPropSet: [UnivProp: .seen, List: [Const: 2015, Const: 2016]]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: [Const: woot.com, Const: 1.2.3.4]], EditPropSet: [UnivProp: .seen, List: [Const: 2015, Const: 2018]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:query, List: [Const: tcp://1.2.3.4, Const: foo*.haha.com, Const: 1]]]',
    'Query: [EditNodeAdd: [AbsProp: test:pivcomp, List: [Const: hehe, Const: haha]], EditPropSet: [RelProp: tick, Const: 2015], EditTagAdd: [TagName: foo, List: [Const: 2014, Const: 2016]]]',
    'Query: [EditNodeAdd: [AbsProp: edge:refs, List: [List: [Const: test:int, Const: 16], List: [Const: test:comp, List: [Const: 9999, Const: greenham]]]]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '--omit-form=meta:source')]]",
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: woot], EditTagAdd: [TagName: foo, List: [Const: 2015, Const: 2018]], EditPropSet: [UnivProp: .seen, List: [Const: 2014, Const: 2016]]]',
    'Query: [EditNodeAdd: [AbsProp: test:comp, List: [Const: 3, Const: foob]], EditTagAdd: [TagName: meep.gorp], EditTagAdd: [TagName: bleep.zlorp], EditTagAdd: [TagName: cond]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: [Const: woot.com, Const: 1.2.3.4]], VarSetOper: [Const: hehe, RelPropValue: [RelProp: fqdn]], FiltOper: [Const: -, RelPropCond: [RelPropValue: [RelProp: fqdn], Const: =, VarValue: [Const: hehe]]]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: [Const: woot.com, Const: 1.2.3.4]], VarSetOper: [Const: hehe, RelPropValue: [RelProp: fqdn]], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: fqdn], Const: =, VarValue: [Const: hehe]]]]',
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: foo, Const: bar]], FiltOper: [Const: +, SubqCond: [Query: [PropPivot: [RelPropValue: [RelProp: lulz], AbsProp: test:str], isjoin=False, FiltOper: [Const: +, TagCond: [TagMatch: baz]]]]], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: test:pivcomp]]]',
    'Query: [LiftProp: [Const: geo:place], FiltOper: [Const: +, AbsPropCond: [AbsProp: geo:place:latlong, Const: *near=, List: [List: [Const: 34.1, Const: -118.3], Const: 10km]]]]',
    'Query: [LiftPropBy: [Const: inet:dns:query, Const: =, List: [Const: tcp://1.2.3.4, Const: , Const: 1]], PropPivot: [RelPropValue: [RelProp: name], AbsProp: inet:fqdn], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: meta:source, Const: abcd], EditTagAdd: [TagName: omit.nopiv], EditNodeAdd: [AbsProp: meta:seen, List: [Const: abcd, List: [Const: test:pivtarg, Const: foo]]]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('--join', '-d', '9', '--traverse-edge')]]",
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: [Const: woot.com, Const: 1.2.3.4]], VarSetOper: [Const: hehe, RelPropValue: [RelProp: fqdn]], LiftPropBy: [Const: inet:fqdn, Const: =, VarValue: [Const: hehe]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], EditPropSet: [RelProp: asn, Const: 10], EditNodeAdd: [AbsProp: meta:seen, List: [Const: abcd, List: [Const: inet:asn, Const: 10]]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: c], SwitchCase: [VarValue: [Const: woot], CaseEntry: [Const: hehe, SubQuery: [Query: [EditTagAdd: [TagName: baz]]]], CaseEntry: [SubQuery: [Query: [EditTagAdd: [TagName: jaz]]]]]]',
    'Query: [LiftPropBy: [Const: geo:place:latlong, Const: *near=, List: [List: [Const: 34.118560, Const: -118.300370], Const: 50m]]]',
    'Query: [LiftPropBy: [Const: ps:person, Const: =, VarValue: [Const: pers]], FormPivot: [AbsProp: edge:wentto], isjoin=False, FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: time], Const: @=, List: [Const: 2014, Const: 2017]]], FormPivot: [AbsProp: geo:place], isjoin=False]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: woot], EditTagAdd: [TagName: foo, List: [Const: 2015, Const: 2018]], EditTagAdd: [TagName: bar], EditPropSet: [UnivProp: .seen, List: [Const: 2014, Const: 2016]]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '-ott=omit.nopiv', '-ott=test')]]",
    "Query: [ForLoop: [VarList: ['fqdn', 'ipv4'], VarValue: [Const: dnsa], SubQuery: [Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: [VarValue: [Const: fqdn], VarValue: [Const: ipv4]]]]]]]",
    'Query: [LiftPropBy: [Const: geo:place:latlong, Const: *near=, List: [List: [Const: 34.118560, Const: -118.300370], Const: 2600m]]]',
    'Query: [LiftProp: [Const: test:comp], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:comp, Const: *range=, List: [List: [Const: 1024, Const: grinch], List: [Const: 4096, Const: zemeanone]]]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], EditPropSet: [RelProp: loc, Const: us], EditNodeAdd: [AbsProp: inet:dns:a, List: [Const: vertex.link, Const: 1.2.3.4]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 4.3.2.1], EditPropSet: [RelProp: loc, Const: zz], EditNodeAdd: [AbsProp: inet:dns:a, List: [Const: example.com, Const: 4.3.2.1]]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '--omit-traversal-form=meta:source')]]",
    'Query: [LiftPropBy: [Const: test:pivcomp, Const: =, List: [Const: hehe, Const: haha]], VarSetOper: [Const: ticktock, TagPropValue: [TagName: foo]], FormPivot: [AbsProp: test:pivtarg], isjoin=False, FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, VarValue: [Const: ticktock]]]]',
    "Query: [EditNodeAdd: [AbsProp: test:comp, List: [Const: 123, Const: test]], EditNodeAdd: [AbsProp: test:comp, List: [Const: 123, Const: duck]], EditNodeAdd: [AbsProp: test:comp, List: [Const: 123, Const: mode]], ForLoop: [VarList: ['fqdn', 'ipv4', 'boom'], VarValue: [Const: dnsa], SubQuery: [Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: [VarValue: [Const: fqdn], VarValue: [Const: ipv4]]]]]]]",
    'Query: [LiftProp: [Const: inet:fqdn], FiltOper: [Const: +, TagCond: [TagMatch: bad]], VarSetOper: [Const: fqdnbad, TagPropValue: [TagName: bad]], FormPivot: [AbsProp: inet:dns:a:fqdn], isjoin=False, FiltOper: [Const: +, RelPropCond: [RelPropValue: [UnivProp: .seen], Const: @=, VarValue: [Const: fqdnbad]]]]',
    'Query: [LiftPropBy: [Const: media:news, Const: =, Const: 00a1f0d928e25729b9e86e2d08c127ce], EditPropSet: [RelProp: summary, Const: ]]',
    'Query: [EditNodeAdd: [AbsProp: edge:refs, List: [List: [Const: test:comp, List: [Const: 2048, Const: horton]], List: [Const: test:comp, List: [Const: 4096, Const: whoville]]]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: .seen], Const: *range=, List: [List: [Const: 20090601, Const: 20090701], List: [Const: 20110905, Const: 20110906]]]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:dns:a, List: [Const: woot.com, Const: 1.2.3.4]], EditNodeAdd: [AbsProp: inet:dns:a, List: [Const: vertex.link, Const: 1.2.3.4]]]',
    'Query: [LiftProp: [Const: edge:refs], FiltOper: [Const: +, RelPropCond: [RelPropValue: [RelProp: n1], Const: *range=, List: [List: [Const: test:comp, List: [Const: 1000, Const: green]], List: [Const: test:comp, List: [Const: 3000, Const: ham]]]]]]',
    'Query: [LiftPropBy: [Const: inet:dns:query, Const: =, List: [Const: tcp://1.2.3.4, Const: foo*.haha.com, Const: 1]], PropPivot: [RelPropValue: [RelProp: name], AbsProp: inet:fqdn], isjoin=False]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: [Const: woot.com, Const: 12.34.56.78]], EditPropSet: [UnivProp: .seen, List: [Const: 201708010123, Const: ?]]]',
    'Query: [LiftProp: [Const: test:int], CmdOper: [Const: noderefs, Const: ()], FiltOper: [Const: +, AbsPropCond: [AbsProp: test:comp, Const: *range=, List: [List: [Const: 1000, Const: grinch], List: [Const: 4000, Const: whoville]]]]]',
    'Query: [EditNodeAdd: [AbsProp: edge:refs, List: [List: [Const: test:comp, List: [Const: 9001, Const: A mean one]], List: [Const: test:comp, List: [Const: 40000, Const: greeneggs]]]]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: [Const: woot.com, Const: 1.2.3.4]], VarSetOper: [Const: seen, UnivPropValue: [UnivProp: .seen]], PropPivot: [RelPropValue: [RelProp: fqdn], AbsProp: inet:fqdn], isjoin=False, EditPropSet: [UnivProp: .seen, VarValue: [Const: seen]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: woot.com], EditNodeAdd: [AbsProp: inet:fqdn, Const: vertex.link], EditNodeAdd: [AbsProp: inet:user, RelPropValue: [RelProp: zone]], FiltOper: [Const: +, HasAbsPropCond: [AbsProp: inet:user]]]',
    'Query: [LiftPropBy: [Const: inet:dns:a, Const: =, List: [Const: woot.com, Const: 12.34.56.78]], EditPropSet: [UnivProp: .seen, List: [Const: 201708010123, Const: 201708100456]]]',
    'Query: [EditNodeAdd: [AbsProp: test:str, Const: c], SwitchCase: [VarValue: [Const: woot], CaseEntry: [Const: hehe, SubQuery: [Query: [EditTagAdd: [TagName: baz]]]], CaseEntry: [Const: haha hoho, SubQuery: [Query: [EditTagAdd: [TagName: faz]]]], CaseEntry: [Const: lolz:lulz, SubQuery: [Query: [EditTagAdd: [TagName: jaz]]]]]]',
    'Query: [EditNodeAdd: [AbsProp: inet:fqdn, Const: hehe.com], EditNodeAdd: [AbsProp: inet:ipv4, Const: 127.0.0.1], EditNodeAdd: [AbsProp: hash:md5, Const: d41d8cd98f00b204e9800998ecf8427e]]',
    "Query: [LiftPropBy: [Const: test:str, Const: =, Const: pennywise], CmdOper: [Const: noderefs, Const: ('-d', '3', '--omit-traversal-tag=omit.nopiv', '--omit-traversal-tag=test')]]",
    'Query: [LiftPropBy: [Const: geo:place, Const: =, Const: abcd], VarSetOper: [Const: latlong, RelPropValue: [RelProp: latlong]], VarSetOper: [Const: radius, RelPropValue: [RelProp: radius]], CmdOper: [Const: spin, Const: ()], LiftPropBy: [Const: tel:mob:telem:latlong, Const: *near=, List: [VarValue: [Const: latlong], Const: 3km]]]',
    'Query: [LiftPropBy: [Const: inet:ipv4, Const: =, Const: 12.34.56.78], LiftPropBy: [Const: inet:fqdn, Const: =, Const: woot.com], EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], EditPropSet: [RelProp: asn, Const: 10101], EditNodeAdd: [AbsProp: inet:fqdn, Const: woowoo.com], EditTagAdd: [TagName: my.tag]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, TagCond: [TagMatch: *]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: -, TagCond: [TagMatch: *]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, TagCond: [TagMatch: foo.*.baz]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, TagCond: [TagMatch: *.bad]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, TagCond: [TagMatch: foo.**.baz]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, TagCond: [TagMatch: **.bar.baz]]]',
    'Query: [LiftProp: [Const: test:str], FiltOper: [Const: +, TagCond: [TagMatch: **.baz]]]',
    "Query: [ForLoop: [Const: foo, VarValue: [Const: foos], SubQuery: [Query: [VarListSetOper: [VarList: ['fqdn', 'ipv4'], FuncCall: [VarDeref: [VarValue: [Const: foo], Const: split], CallArgs: [Const: |], CallKwargs: []]], EditNodeAdd: [AbsProp: inet:dns:a, List: [VarValue: [Const: fqdn], VarValue: [Const: ipv4]]]]]]]",
    'Query: [LiftProp: [Const: test:int]]',
    'Query: [LiftProp: [Const: test:int]]',
    'Query: [LiftProp: [Const: test:int]]',
    'Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], SwitchCase: [VarValue: [Const: foo], CaseEntry: [Const: bar, SubQuery: [Query: [EditTagAdd: [TagName: hehe.haha]]]], CaseEntry: [Const: baz faz, SubQuery: [Query: []]]]]',
    "Query: [LiftProp: [Const: inet:fqdn], CmdOper: [Const: graph, Const: ('--degrees', '2', '--filter', '{ -#nope }', '--pivot', '{ <- meta:seen <- meta:source }', '--form-pivot', 'inet:fqdn', '{<- * | limit 20}', '--form-pivot', 'inet:fqdn', '{-> * | limit 20}', '--form-filter', 'inet:fqdn', '{-inet:fqdn:issuffix=1}', '--form-pivot', 'syn:tag', '{-> *}', '--form-pivot', '*', '{-> #}')]]",
    'Query: [ForLoop: [Const: foo, VarValue: [Const: foos], SubQuery: [Query: [EditNodeAdd: [AbsProp: inet:ipv4, Const: 1.2.3.4], SwitchCase: [VarValue: [Const: foo], CaseEntry: [Const: bar, SubQuery: [Query: [EditTagAdd: [TagName: ohai], BreakOper: []]]], CaseEntry: [Const: baz, SubQuery: [Query: [EditTagAdd: [TagName: visi], ContinueOper: []]]]], EditNodeAdd: [AbsProp: inet:ipv4, Const: 5.6.7.8], EditTagAdd: [TagName: hehe]]]]]',
    'Query: [LiftPropBy: [Const: test:int, Const: =, Const: 1234], EditNodeAdd: [AbsProp: test:str, FuncCall: [VarDeref: [VarValue: [Const: node], Const: value], CallArgs: [], CallKwargs: []]], FiltOper: [Const: -, HasAbsPropCond: [AbsProp: test:int]]]',
    'Query: [LiftPropBy: [Const: test:int, Const: =, Const: 1234], EditNodeAdd: [AbsProp: test:str, FuncCall: [VarDeref: [VarValue: [Const: node], Const: form], CallArgs: [], CallKwargs: []]], FiltOper: [Const: -, HasAbsPropCond: [AbsProp: test:int]]]',
    "Query: [ForLoop: [Const: foo, VarValue: [Const: foos], SubQuery: [Query: [VarListSetOper: [VarList: ['fqdn', 'ipv4'], FuncCall: [VarDeref: [VarValue: [Const: foo], Const: split], CallArgs: [Const: |], CallKwargs: []]], EditNodeAdd: [AbsProp: inet:dns:a, List: [VarValue: [Const: fqdn], VarValue: [Const: ipv4]]]]]]]",
    'Query: [EditNodeAdd: [AbsProp: test:int, VarDeref: [VarValue: [Const: hehe], Const: haha]]]',
    "Query: [VarListSetOper: [VarList: ['tick', 'tock'], UnivPropValue: [UnivProp: .seen]]]",
    'Query: [ForLoop: [Const: tag, FuncCall: [VarDeref: [VarValue: [Const: node], Const: tags], CallArgs: [], CallKwargs: []], SubQuery: [Query: [FormPivot: [AbsProp: test:int], isjoin=False, EditTagAdd: [VarValue: [Const: tag]]]]]]',
    'Query: [ForLoop: [Const: tag, FuncCall: [VarDeref: [VarValue: [Const: node], Const: tags], CallArgs: [Const: fo*], CallKwargs: []], SubQuery: [Query: [FormPivot: [AbsProp: test:int], isjoin=False, EditTagDel: [VarValue: [Const: tag]]]]]]',
]

class GrammarTest(s_t_utils.SynTest):

    def test_grammar(self):
        grammar = open('synapse/lib/storm.g').read()

        parser = lark.Lark(grammar, start='query', debug=True)

        for i, query in enumerate(_Queries):
            try:

                parser.parse(query)
                # print(f'{tree.pretty()}\n)')
            except (lark.ParseError, lark.UnexpectedCharacters):
                # print(f'Failure on parsing {{{query}}}')
                raise

    async def test_parser(self):
        self.maxDiff = None
        # import IPython; IPython.embed()
        for i, query in enumerate(_Queries):
            # if i < 33:
            #     continue
            print(f'{i:3}: {{{query}}}: ', end='')
            if i > 250:
                # FIXME:  increase as we get more
                break
            parser = s_syntax2.Parser(query)
            tree = parser.query()

            print(str(tree))
            self.eq(str(tree), _ParseResults[i])

def gen_parse_list():
    import synapse.lib.syntax as s_syntax

    retn = []
    for i, query in enumerate(_Queries):
        parser = s_syntax.Parser(query)
        tree = parser.query()
        retn.append(str(tree))
    return retn

def print_parse_list():
    for i in gen_parse_list():
        print(f'    {repr(i)},')
