#
# This dockerfile is designed for use as a GDB debuggable container
# See the example at the following for more information
# https://github.com/vertexproject/pydebug
#
# vim:set ft=dockerfile:
FROM vertexproject/synapse-base-image:py36-debug

# We're using a debug image - set the default logging to DEBUG level
ENV SYN_DMON_LOG_LEVEL="DEBUG"

COPY . /root/git/synapse
RUN mkdir /syndata \
 && cd /root/git/synapse && python setup.py install \
 && cp synapse/docker/cortex/ram_dmon.json /syndata/dmon.json

VOLUME /syndata
VOLUME /root/git/synapse

WORKDIR /root/git/synapse
EXPOSE 47322
ENTRYPOINT ["python", "-m", "synapse.tools.dmon", "/syndata/dmon.json"]
