name: GitSync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: vertexproject/git-repo-sync@v0.1.0
      with:
        target-url: https://${{ secrets.SYNC_TARGET_HOST }}/${{ github.repository }}.git
        target-username: ${{ secrets.SYNC_TARGET_USERNAME }}
        target-token: ${{ secrets.SYNC_TARGET_TOKEN }}